In [1]:
import numpy as np
import pandas as pd
from natsort import natsorted
from glob import glob
import nltk

In [2]:
n_w = ['1', '2', '3', '4', '5', '6', '7', '8', 'A', 'B', 'C', 'D', 'E']

In [3]:
data = pd.read_csv('output/Wave1-8_A-E.csv', dtype=str, keep_default_na=False, na_values=['','nan'])

data = data.reindex(natsorted(data.columns), axis=1)

In [4]:
data = data.loc[~data['PROLIFIC_PID'].isna()]

In [5]:
data.to_csv('output/Wave1-8_A-E.csv', index=False)

In [6]:
data.loc[data['wave']=='1', 'DemC2']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1792    NaN
1793    NaN
1794    NaN
1795    NaN
1796    NaN
Name: DemC2, Length: 1797, dtype: object

In [7]:
valid = pd.read_csv('output/validation_interquartile_classification.csv')

/home/andy/anaconda3/envs/covid-dynamic/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (198) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [282]:
data.loc[data['wave']=='B',['NIHE1_9', 'DemC25', 'DISG1.2_23', 'DISG1.1_23', 'DISG2.2_23', 'ReSe1_23', 'Fed_13', 'RW23', 'GFPS2_11', 'EES1_32']]

,NIHE1_9,DemC25,DISG1.2_23,DISG1.1_23,DISG2.2_23,ReSe1_23,Fed_13,RW23,GFPS2_11,EES1_32
10942,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10943,3.0,NaN,2.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0
10944,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10945,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10946,4.0,NaN,5.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10947,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10948,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10949,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10950,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10951,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10952,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10953,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10954,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10955,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10956,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10957,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10958,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10959,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10960,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10961,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10962,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10963,4.0,NaN,3.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10964,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10965,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10966,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10967,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10968,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10969,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10970,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10971,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10972,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10973,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10974,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10975,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10976,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10977,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10978,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10979,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10980,5.0,NaN,4.0,NaN,NaN,4.0,6.0,NaN,NaN,1.0
10981,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10982,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10983,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10984,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10985,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10986,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10987,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10988,4.0,NaN,5.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10989,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0
10990,4.0,NaN,4.0,NaN,NaN,4.0,7.0,NaN,NaN,5.0

In [8]:
def cal_completed(incld, dat, w):
    finished = dat.loc[dat['wave']==str(w), ['PROLIFIC_PID', 'V5']]
    n_completed = len(finished.loc[finished['V5']=='1'])
    r_completed = n_completed/len(incld)
    return(n_completed, r_completed)

def incld_lst(s_in, s_w):
    #  Retrun a True False series indicating which record in w5 included list is not in the 
    #  inputted included list (w1, w2, w3, w4)
    return s_in.isin(s_w)

def attent_check(dat, w):
    
    # Extract the responses for the attention check questions    
    attent_vars = ['NIHE1_9', 'DemC25', 'DISG1.2_23', 'DISG1.1_23', 'DISG2.2_23', 'ReSe1_23', 'Fed_13', 'RW23', 'GFPS2_11', 'EES1_32']
    attent_df = dat.loc[dat['wave']==w, attent_vars]
    attent_df = attent_df.dropna(axis=1, how='all')
    
    # TODO: check whether the user fail the attention check questions.
    # Attention check values
    attent_chk = {'NIHE1_9': '4.0',
              'DemC25': '3.0',
              'DISG1.2_23': '4.0',
              'DISG1.1_23': '2.0',
              'DISG2.2_23': '4.0',
              'ReSe1_23': '4.0',
              'Fed_13': '7.0', 
              'RW23': '2.0',
              'GFPS2_11': '1.0',
              'EES1_32': '5.0',}
    
    attent_cols = attent_df.columns
    n = len(attent_df)
    nan_array = np.empty(n)
    nan_array[:] = np.nan
    
    out = pd.DataFrame({'failed_att_qns_1': nan_array,
                        'failed_att_qns_2': nan_array,
                        'failed_att_qns_3': nan_array,
                        'failed_att_qns_4': nan_array,
                        'failed_att_qns_5': nan_array})
    
    out_cols = out.columns
    
    print(out_cols)
    print(attent_cols)
    
    for i in range(len(attent_cols)):
        tmp = (attent_df[attent_cols[i]] != attent_chk[attent_cols[i]])
        out[out_cols[i]] = tmp.values
    return out

def ext_nouns(txt):
    # A package call textblob allows us to easily extract nouns
#     if txt is np.nan:
#         return np.nan
#     else:
#         blob = TextBlob(txt)
#         return blob.noun_phrases
    # function to test if something is a noun
    if txt is np.nan:
        return np.nan
    else:
        is_noun = lambda pos: pos[:2] == 'NN'
        # do the nlp stuff
        tokenized = nltk.word_tokenize(txt)
        nouns = [word for (word, pos) in nltk.pos_tag(tokenized) if is_noun(pos)]
        return nouns

    
def ext_verbs(txt):

    if txt is np.nan:
        return np.nan
    else:
        is_noun = lambda pos: pos[:2] == 'VB'
        # do the nlp stuff
        tokenized = nltk.word_tokenize(txt)
        nouns = [word for (word, pos) in nltk.pos_tag(tokenized) if is_noun(pos)]
        return nouns


def count_nouns(ls):
    if ls is np.nan:
        return np.nan
    else:
        return len(ls)

# Map the data collected in w1 to other weeks
def map_w1_to_other(col_name, validation):
    dictionary = validation.loc[validation['wave']=='1', ['PROLIFIC_PID', col_name]].set_index('PROLIFIC_PID').to_dict()
    validation.loc[validation[col_name].isna(), col_name] = validation.loc[validation[col_name].isna(), 'PROLIFIC_PID'].map(dictionary[col_name])
    return validation

# Map the prolific demographic data to the validation participants
def map_prolific_to_valid(prolific_name, prolific_demo, valid_name, validation):
    dictionary = prolific_demo.loc[:, ['participant_id', prolific_name]].set_index('participant_id').to_dict()
    validation[valid_name] = validation['PROLIFIC_PID'].map(dictionary[prolific_name])
    return validation

# Pipeline to create the validation file

### 1. Time

In [9]:
validation = data.loc[:,['PROLIFIC_PID', 'wave']]

In [10]:
validation.head()

               PROLIFIC_PID wave
0  5df82e8739bcde5dd044f741    1
1  5c7e91c1973c990016ea72b0    1
2  5e753094e8a6f10a9805ed9a    1
3  5e67052c757e6149c38ce468    1
4  5e7745990fd39b2a816ec341    1

In [11]:
s = data.loc[:,'V4'].apply(pd.Timestamp)-data.loc[:,'V3'].apply(pd.Timestamp)

In [12]:
validation.loc[:,'total_time'] = s.apply(lambda x: x.seconds/60)

## 2. Attention check questions

In [13]:
attent_chk_qns = ['failed_att_qns_1','failed_att_qns_2','failed_att_qns_3', 'failed_att_qns_4', 'failed_att_qns_5']

validation.loc[:, attent_chk_qns[0]] = np.nan
validation.loc[:, attent_chk_qns[1]] = np.nan
validation.loc[:, attent_chk_qns[2]] = np.nan
validation.loc[:, attent_chk_qns[3]] = np.nan
validation.loc[:, attent_chk_qns[4]] = np.nan


for w in n_w:
    validation.loc[validation['wave']==w, attent_chk_qns] = attent_check(data, w).values

Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['DemC25', 'DISG1.1_23', 'RW23'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['DISG1.1_23', 'RW23'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['NIHE1_9', 'ReSe1_23', 'RW23'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['DISG2.2_23', 'Fed_13', 'EES1_32'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['NIHE1_9', 'DISG1.2_23', 'Fed_13'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['DISG2.2_23', 'ReSe1_23', 'Fed_13'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['DISG2.2_23', 'RW23', 'GFPS2_11'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['NIHE1_9', 'DISG1.2_23', 'ReSe1_23'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['NIHE1_9', 'DemC25', 'DISG1.1_23', 'RW23'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['NIHE1_9', 'DISG1.2_23', 'ReSe1_23', 'Fed_13', 'EES1_32'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['DISG2.2_23', 'ReSe1_23', 'Fed_13'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['DISG2.2_23', 'RW23', 'GFPS2_11'], dtype='object')
Index(['failed_att_qns_1', 'failed_att_qns_2', 'failed_att_qns_3',
       'failed_att_qns_4', 'failed_att_qns_5'],
      dtype='object')
Index(['NIHE1_9', 'DISG1.2_23', 'ReSe1_23'], dtype='object')

In [14]:
validation.loc[validation['wave']=='A'].head()

,PROLIFIC_PID,wave,total_time,failed_att_qns_1,failed_att_qns_2,failed_att_qns_3,failed_att_qns_4,failed_att_qns_5
10873,CC0186,A,43.0,False,False,True,False,NaN
10874,CC0144,A,147.0,True,False,False,False,NaN
10875,CC0172,A,114.0,True,False,False,False,NaN
10876,CC0165,A,15.0,False,False,False,False,NaN
10877,CC0117,A,81.0,False,False,False,False,NaN

## 3. Other variables

In [15]:
# completed
validation.loc[:,'completed'] = data.loc[:, 'V5']

In [16]:
# include lists
incld_paths = {'w1': 'Working_Data/participant_lists/w1_included.csv',
               'w2': 'Working_Data/participant_lists/w2_includeList_postw1_analysis.csv',
               'w3': 'Working_Data/participant_lists/w3_includeList_postw2_analysis.csv',
               'w4': 'Working_Data/participant_lists/w4_includeList_postw3_analysis.csv',
               'w5': 'Working_Data/participant_lists/w5_includeList_postw4_analysis.csv'}

In [17]:
for i in range(5):
    wave = 'w'+ str(i+1)
    var_name = 'in_include_list_' + wave
    validation.loc[:,var_name] = incld_lst(validation['PROLIFIC_PID'], pd.read_csv(incld_paths[wave], header=None).values.flatten())

In [18]:
validation['PROLIFIC_PID'] = validation['PROLIFIC_PID'].str.replace(' ', '')

In [19]:
# demographic data
demo_dict = {'DemC9': "dem_race",
             'DemC8': "dem_ethnicity",
             'DemW3': "dem_state",
             'DemC23': "dem_education",
             'DemW18': "dem_weekly_income_now",
             'DemC44': "dem_weekly_income_2019",
             'DemM6': "dem_partisanship",
             'DemW10': "dem_employ_status_now",
             'DemC33': "dem_employ_status_2019",
             'DemC1': "dem_age"}

def choose_nona(x):
    #print(x.isna().values)
    a = x[~x.isna().values]
    out = np.nan
    if a.size != 0:
        out = a[0]
    
    return out

DemW18 = ['DemW18_R1', 'DemW18_R2', 'DemW18.2']
DemC44 = ['Q28', 'DemC44']
DemW10 = ['DemW10_R1', 'DemW10_R2', 'DemW10_R3', 'DemW10_R4']
DemC33 = ['DemC33_R1', 'DemC33_R2']

In [20]:
s = data.loc[:, DemW18].apply(choose_nona, axis=1)
validation['DemW18'] = s

In [21]:
s = data.loc[:, DemC44].apply(choose_nona, axis=1)
validation['DemC44'] = s

In [22]:
s = data.loc[:, DemW10].apply(choose_nona, axis=1)
validation['DemW10'] = s

In [23]:
s = data.loc[:, DemC33].apply(choose_nona, axis=1)
validation['DemC33'] = s

In [24]:
other_vars = ['DemC9', 'DemC1','DemC8', 'DemW3', 'DemC23', 'DemM6']
validation[other_vars] = data.loc[:, other_vars]

In [25]:
# Map the data collected in w1 to other weeks
cols_w1 = ['DemC9', 'DemC8', 'DemC1', 'DemW3', 'DemC23', 'DemC44','DemC33'] 
for col in cols_w1:
    validation = map_w1_to_other(col, validation)

In [26]:
# Convert col names
validation = validation.rename(columns=demo_dict)

In [27]:
# Read in prolific demographic data
prolific_demo_paths = glob('Working_Data/W1_Prolific/*.csv')
pilot_prolific_demo_paths = glob('Working_Data/Pilot30_Prolific/*.csv')

In [28]:
prolific_demo_paths = prolific_demo_paths + pilot_prolific_demo_paths

In [29]:
dats = []
for path in prolific_demo_paths:
    dat = pd.read_csv(path)
    dats.append(dat)

all_prolific_demo = pd.concat(dats, axis=0).reset_index(drop=True)

In [30]:
all_prolific_demo.loc[all_prolific_demo['participant_id']=='5e35a30bde69fe54124579f2']

,session_id,participant_id,status,started_datetime,completed_date_time,time_taken,age,num_approvals,num_rejections,prolific_score,...,entered_code,Country of Birth,Current Country of Residence,Current U.S state of residence,Employment Status,First Language,Fluent languages,Nationality,Sex,Student Status
2048,5e89dc057db7b66708e39d62,5e35a30bde69fe54124579f2,AWAITING REVIEW,2020-04-05 13:24:21.228000,2020-04-05 14:33:41.151000,4159.923,32,97,1,100,...,55A2250F,United States,United States,NaN,Full-Time,English,English,United States,Male,No

In [31]:
tmp_dict = {'Sex': "prlfc_dem_sex",
            'age': "prlfc_dem_age",
            'Employment Status': "prlfc_dem_employ_status",
            'Current U.S state of residence': "prlfc_dem_state"}

In [32]:
for col in list(tmp_dict.keys()):
    validation = map_prolific_to_valid(col, all_prolific_demo, tmp_dict[col], validation)

In [33]:
validation['prlfc_dem_employ_status'].unique()

array(['Unemployed (and job seeking)',
       "Not in paid work (e.g. homemaker', 'retired or disabled)",
       'Full-Time', 'CONSENT REVOKED', 'Other', 'Part-Time',
       'Not in paid work (e.g. homemaker, retired or disabled)', nan,
       'DATA EXPIRED', 'Due to start a new job within the next month'],
      dtype=object)

In [34]:
# Create a mapping dictionary to refer back to the 
w1_dict = {'1.0': 'Employed',
           '2.0': 'Unemployed',
           '3.0': 'Retired+'}

w2_6_dict = {'1.0': 'Employed',
             '2.0': 'Employed',
             '3.0': 'Unemployed',
             '4.0': 'Retired+',
             '5.0': 'Retired+'}

w7_dict = {'1.0': 'Employed',
           '2.0': 'Employed',
           '3.0': 'Unemployed', 
           '4.0': 'Retired+',
           '5.0': 'Retired+',
           '6.0': 'Retired+',
           '7.0': 'Retired+'}

es_dict = {'Full-Time': 'Employed',
           'Part-Time': 'Employed',
           'Unemployed (and job seeking)': 'Unemployed',
           'Other': 'Retired+', 
           "Not in paid work (e.g. homemaker', 'retired or disabled)": 'Retired+',
           'DATA EXPIRED': np.nan,
           'Due to start a new job within the next month': 'Employed',
           'Not in paid work (e.g. homemaker, retired or disabled)': 'Retired+',
           'CONSENT REVOKED': np.nan}

In [35]:


s_tmp = validation.loc[:, 'dem_employ_status_now'].copy()
p_tmp = validation.loc[:, 'prlfc_dem_employ_status'].map(es_dict)
for w in n_w:
    if w == '1':
        s_tmp.loc[validation['wave'] == w] = validation.loc[validation['wave'] == w, 'dem_employ_status_now'].map(w1_dict).values
    elif w in ['2', '3', '4', '5', '6', 'A', 'B', 'C']:
        s_tmp.loc[validation['wave'] == w] = validation.loc[validation['wave'] == w, 'dem_employ_status_now'].map(w2_6_dict).values
    else:
        s_tmp.loc[validation['wave'] == w] = validation.loc[validation['wave'] == w, 'dem_employ_status_now'].map(w7_dict).values

In [36]:
validation['match_dem_employ_status'] = s_tmp == p_tmp

In [37]:
# Match age
validation["match_dem_age"] = ((validation['dem_age'].astype(float)+1) >= validation['prlfc_dem_age']) & ((validation['dem_age'].astype(float)-1) <= validation['prlfc_dem_age'])

In [38]:
validation.loc[(validation['wave']=='1') & (validation['prlfc_dem_age'].isna())].to_csv('not_in_prolific.csv', index=False)

In [39]:
# Process state
validation['dem_state'] = validation['dem_state'].str.replace(r' - [A-Z][A-Z]', '')
validation["prlfc_dem_state"] = validation['prlfc_dem_state'].str.replace(r' \([A-Z][A-Z]\)', '')

# Match state
validation["match_dem_state"] = validation['dem_state'] == validation['prlfc_dem_state']

In [40]:
# Task
validation['task_completed'] = data['Tsk4']

In [41]:
import nltk
#nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/andy/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [42]:
# Text nouns
var_names = ["DemW21_1_TEXT", "DemW21_2_TEXT", "DemW21_3_TEXT", "RW7_1_TEXT", "RW7_2_TEXT", "RW7_3_TEXT"]

for var in var_names:
    validation[var+'_no_nouns'] = data[var].apply(ext_nouns).apply(count_nouns)

In [43]:
for var in var_names:
    validation[var+'_no_verbs'] = data[var].apply(ext_verbs).apply(count_nouns)

In [44]:
data.loc[4, "RW7_1_TEXT"]

'covid-19 quarantine '

In [45]:
validation.to_csv('output/validation.csv', index=False)

## 4. response string length

In [46]:

def long_string(row):
    # Return a list of response string length
    # The calculation of MaxLongString, meanLongString and countLongString can be calculated from this list
    count_ls = []
    string_len = 1
    for i in range(1, len(row)):
        #print(i)
        if np.isnan(float(row[i])):
            # If the row contains all nas, then will append an empty list
#             if string_len > 1:
#                 count_ls.append(string_len)
#                 string_len = 1
            continue
        elif row[i] == row[i-1]:
            string_len += 1
        elif row[i-1] is not np.nan:
            count_ls.append(string_len)
            string_len = 1
    
    if ~np.all(np.isnan([float(x) for x in row])):
        count_ls.append(string_len)
    return np.array(count_ls)


def get_max(ls):
    if ls.size == 0:
        return np.nan
    else:
        return ls[np.argmax(ls)]
    
    
def get_mean(ls):
    if ls.size == 0:
        return np.nan
    else:
        return np.mean(ls)
    
def count_greater_than_5(ls):
    if ls.size == 0:
        return np.nan
    else:
        return np.sum(ls >= 5)
    
def response_string(dat, name, validation):
    s_long_string = dat.apply(long_string, axis=1)
    validation['maxLongString_'+name] = s_long_string.apply(get_max)
    validation['meanLongString_'+name] = s_long_string.apply(get_mean)
    validation['countLongString_'+name] = s_long_string.apply(count_greater_than_5)
    
    return validation, s_long_string, ['maxLongString_'+name, 'meanLongString_'+name, 'countLongString_'+name]

def inspect(dat, validation, s_long_string, input_vars, output_vars, inspect_w='1'):
    print(dat.loc[dat['wave']==inspect_w, input_vars].head())
    print(s_long_string[validation['wave']==inspect_w].head())
    print(validation.loc[validation['wave']==inspect_w, output_vars].head())


def process_na(dat, var_names):
    for w in np.unique(dat['wave']):
        for var in var_names:
            if np.sum(~dat.loc[dat['wave']==w, var].isna())>0:
                dat.loc[dat['wave']==w,var] = dat.loc[dat['wave']==w, var].fillna(0)
        
#         if((np.sum(np.sum(~dat.loc[dat['wave']==w, var_names].isna()))) > 0) and flag:
#             dat.loc[dat['wave']==w, var_names] = dat.loc[dat['wave']==w, var_names].fillna(0)
        
    return dat

def run_analysis(data, validation, name, input_vars, inspect_w='1'):
    data = process_na(data, input_vars)
    input_dat = data.loc[:, input_vars]
    validation, s, output_vars = response_string(input_dat, name, validation)
    
    if inspect_w:
        inspect(data, validation, s, input_vars, output_vars, inspect_w=inspect_w)
    
    return validation, data


def construct_vars(prefix, n, postfix=None, skip=[]):
    ls = []
    for i in range(n):
        if (i+1) not in skip:
            out = prefix + str(i+1)
            if postfix:
                out = out + postfix
            ls.append(out)
    return ls

In [47]:
name = 'PANA'
input_vars = data.loc[:,'PANA1_1':'PANA1_20'].columns
validation, data = run_analysis(data, validation, name, input_vars)

  PANA1_1 PANA1_2 PANA1_3 PANA1_4 PANA1_5 PANA1_6 PANA1_7 PANA1_8 PANA1_9  \
0     4.0     2.0     3.0     1.0     4.0     1.0     1.0     1.0     3.0
1     3.0     4.0     1.0     2.0     1.0     1.0     3.0     1.0     1.0
2     3.0     2.0     1.0     1.0     2.0     1.0     2.0     1.0     2.0
3     3.0     2.0     1.0     1.0     1.0     2.0     3.0     1.0     1.0
4     4.0     4.0     4.0     3.0     3.0     4.0     4.0     4.0     3.0

  PANA1_10 PANA1_11 PANA1_12 PANA1_13 PANA1_14 PANA1_15 PANA1_16 PANA1_17  \
0      5.0      2.0      5.0      1.0      5.0      2.0      5.0      5.0
1      1.0      2.0      5.0      1.0      1.0      3.0      1.0      5.0
2      2.0      2.0      1.0      1.0      2.0      1.0      3.0      4.0
3      1.0      2.0      2.0      1.0      1.0      3.0      2.0      2.0
4      4.0      2.0      3.0      3.0      3.0      4.0      3.0      4.0

  PANA1_18 PANA1_19 PANA1_20
0      3.0      4.0      1.0
1      3.0      3.0      3.0
2      1.0      1.0      2.0
3      1.0      2.0      3.0
4      3.0      4.0      1.0
0    [1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, ...
1           [1, 1, 1, 1, 2, 1, 3, 1, 1, 2, 1, 1, 1, 3]
2        [1, 1, 2, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 2, 1]
3              [1, 1, 3, 1, 1, 3, 2, 2, 1, 2, 1, 1, 1]
4              [3, 2, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1]
dtype: object
   maxLongString_PANA  meanLongString_PANA  countLongString_PANA
0                   3             1.176471                     0
1                   3             1.428571                     0
2                   3             1.333333                     0
3                   3             1.538462                     0
4                   3             1.538462                     0

In [48]:
name = 'STAI_state'
input_vars = data.loc[:,'AnxS1_1':'AnxS1_20'].columns
validation, data = run_analysis(data, validation, name, input_vars, inspect_w='4')

     AnxS1_1 AnxS1_2 AnxS1_3 AnxS1_4 AnxS1_5 AnxS1_6 AnxS1_7 AnxS1_8 AnxS1_9  \
4757     2.0     2.0     1.0     2.0     2.0     1.0     2.0     1.0     1.0
4758     4.0     4.0     1.0     1.0     4.0     1.0     3.0     4.0     1.0
4759     4.0     4.0     1.0     1.0     4.0     1.0     4.0     4.0     4.0
4760     3.0     2.0     1.0     1.0     3.0     1.0     1.0     1.0     1.0
4761     4.0     4.0     1.0     1.0     4.0     1.0     1.0     4.0     1.0

     AnxS1_10 AnxS1_11 AnxS1_12 AnxS1_13 AnxS1_14 AnxS1_15 AnxS1_16 AnxS1_17  \
4757      2.0      1.0      1.0      1.0      1.0      2.0      2.0      1.0
4758      4.0      4.0      2.0      1.0      1.0      4.0      4.0      2.0
4759      4.0      2.0      1.0      1.0      1.0      4.0      4.0      4.0
4760      2.0      1.0      1.0      1.0      1.0      3.0      2.0      1.0
4761      4.0      3.0      1.0      1.0      1.0      4.0      4.0      1.0

     AnxS1_18 AnxS1_19 AnxS1_20
4757      1.0      2.0      2.0
4758      1.0      4.0      4.0
4759      1.0      4.0      4.0
4760      1.0      3.0      2.0
4761      1.0      4.0      4.0
4757             [2, 1, 2, 1, 1, 2, 1, 4, 2, 2, 2]
4758    [2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2]
4759                [2, 2, 1, 1, 4, 1, 3, 3, 1, 2]
4760          [1, 1, 2, 1, 4, 1, 4, 1, 1, 2, 1, 1]
4761          [2, 2, 1, 2, 1, 1, 1, 1, 3, 2, 2, 2]
dtype: object
      maxLongString_STAI_state  meanLongString_STAI_state  \
4757                         4                   1.818182
4758                         2                   1.428571
4759                         4                   2.000000
4760                         4                   1.666667
4761                         3                   1.666667

      countLongString_STAI_state
4757                           0
4758                           0
4759                           0
4760                           0
4761                           0

In [49]:
# Disgust
name = 'disgust_COVID'
input_vars = data.loc[:,'DISG1.2_1':'DISG1.2_22'].columns
validation, data = run_analysis(data, validation, name, input_vars, inspect_w='7')

     DISG1.2_1 DISG1.2_2 DISG1.2_3 DISG1.2_4 DISG1.2_5 DISG1.2_6 DISG1.2_7  \
8608       NaN       NaN       NaN       NaN       NaN       NaN       NaN
8609       NaN       NaN       NaN       NaN       NaN       NaN       NaN
8610       NaN       NaN       NaN       NaN       NaN       NaN       NaN
8611       NaN       NaN       NaN       NaN       NaN       NaN       NaN
8612       NaN       NaN       NaN       NaN       NaN       NaN       NaN

     DISG1.2_8 DISG1.2_9 DISG1.2_10 DISG1.2_11 DISG1.2_12 DISG1.2_14  \
8608       NaN       NaN        NaN        NaN        NaN        NaN
8609       NaN       NaN        NaN        NaN        NaN        NaN
8610       NaN       NaN        NaN        NaN        NaN        NaN
8611       NaN       NaN        NaN        NaN        NaN        NaN
8612       NaN       NaN        NaN        NaN        NaN        NaN

     DISG1.2_15 DISG1.2_17 DISG1.2_18 DISG1.2_19 DISG1.2_20 DISG1.2_21  \
8608        4.0        5.0        4.0        5.0        3.0        3.0
8609        1.0        1.0        1.0        4.0        1.0        2.0
8610        5.0        3.0        4.0        5.0        1.0        3.0
8611        5.0        4.0        4.0        5.0        1.0        2.0
8612        2.0        4.0        1.0        5.0        1.0        1.0

     DISG1.2_22
8608        5.0
8609        4.0
8610        4.0
8611        5.0
8612        3.0
8608       [1, 1, 1, 1, 2, 1]
8609          [3, 1, 1, 1, 1]
8610    [1, 1, 1, 1, 1, 1, 1]
8611       [1, 2, 1, 1, 1, 1]
8612       [1, 1, 1, 1, 2, 1]
dtype: object
      maxLongString_disgust_COVID  meanLongString_disgust_COVID  \
8608                            2                      1.166667
8609                            3                      1.400000
8610                            1                      1.000000
8611                            2                      1.166667
8612                            2                      1.166667

      countLongString_disgust_COVID
8608                              0
8609                              0
8610                              0
8611                              0
8612                              0

In [50]:
# fear
name = 'fear_COVID'
input_vars = data.loc[:,'Fear2_1':'Fear2_7'].columns
validation, data = run_analysis(data, validation, name, input_vars)

  Fear2_1 Fear2_2 Fear2_3 Fear2_4 Fear2_5 Fear2_6 Fear2_7
0     2.0     2.0     2.0     3.0     1.0     1.0     4.0
1     5.0     5.0     5.0     5.0     3.0     3.0     5.0
2     3.0     4.0     1.0     2.0     3.0     4.0     5.0
3     4.0     5.0     3.0     4.0     2.0     2.0     5.0
4     2.0     2.0     4.0     2.0     2.0     3.0     3.0
0             [3, 1, 2, 1]
1                [4, 2, 1]
2    [1, 1, 1, 1, 1, 1, 1]
3       [1, 1, 1, 1, 2, 1]
4             [2, 1, 2, 2]
dtype: object
   maxLongString_fear_COVID  meanLongString_fear_COVID  \
0                         3                   1.750000
1                         4                   2.333333
2                         1                   1.000000
3                         2                   1.166667
4                         2                   1.750000

   countLongString_fear_COVID
0                           0
1                           0
2                           0
3                           0
4                           0

In [51]:
# EMSB
name = 'EMSB'
input_vars = data.loc[:,"EMSB1_1":"EMSB1_9"].columns
validation, data = run_analysis(data, validation, name, input_vars)

  EMSB1_1 EMSB1_2 EMSB1_3 EMSB1_4 EMSB1_5 EMSB1_6 EMSB1_7 EMSB1_8 EMSB1_9
0     1.0     9.0     1.0     9.0     1.0     9.0     1.0     1.0     1.0
1     5.0     9.0     7.0     9.0     5.0     9.0     5.0     1.0     1.0
2     9.0     8.0     3.0     8.0     5.0     9.0     2.0     1.0     1.0
3     5.0     4.0     5.0     6.0     7.0     6.0     5.0     4.0     5.0
4     1.0     9.0     1.0     9.0     1.0     9.0     1.0     1.0     1.0
0          [1, 1, 1, 1, 1, 1, 3]
1       [1, 1, 1, 1, 1, 1, 1, 2]
2       [1, 1, 1, 1, 1, 1, 1, 2]
3    [1, 1, 1, 1, 1, 1, 1, 1, 1]
4          [1, 1, 1, 1, 1, 1, 3]
dtype: object
   maxLongString_EMSB  meanLongString_EMSB  countLongString_EMSB
0                 3.0             1.285714                   0.0
1                 2.0             1.125000                   0.0
2                 2.0             1.125000                   0.0
3                 1.0             1.000000                   0.0
4                 3.0             1.285714                   0.0

In [52]:
# EMSC
name = 'EMSC'
input_vars = data.loc[:,"EMSC1_1":"EMSC1_9"].columns
validation, data = run_analysis(data, validation, name, input_vars)

  EMSC1_1 EMSC1_2 EMSC1_3 EMSC1_4 EMSC1_5 EMSC1_6 EMSC1_7 EMSC1_8 EMSC1_9
0     1.0     9.0     1.0     9.0     1.0     9.0     1.0     1.0     1.0
1     1.0     9.0     1.0     9.0     1.0     9.0     1.0     9.0     1.0
2     5.0     3.0     2.0     6.0     2.0     5.0     1.0     3.0     1.0
3     2.0     8.0     1.0     9.0     5.0     6.0     1.0     1.0     5.0
4     5.0     6.0     1.0     6.0     8.0     6.0     1.0     1.0     1.0
0          [1, 1, 1, 1, 1, 1, 3]
1    [1, 1, 1, 1, 1, 1, 1, 1, 1]
2    [1, 1, 1, 1, 1, 1, 1, 1, 1]
3       [1, 1, 1, 1, 1, 1, 2, 1]
4          [1, 1, 1, 1, 1, 1, 3]
dtype: object
   maxLongString_EMSC  meanLongString_EMSC  countLongString_EMSC
0                 3.0             1.285714                   0.0
1                 1.0             1.000000                   0.0
2                 1.0             1.000000                   0.0
3                 2.0             1.125000                   0.0
4                 3.0             1.285714                   0.0

In [53]:
data[data.loc[:,'NIHE1_1':'NIHE1_8'].columns]

      NIHE1_1 NIHE1_2 NIHE1_3 NIHE1_4 NIHE1_5 NIHE1_6 NIHE1_7 NIHE1_8
0         2.0     2.0     2.0     2.0     2.0     2.0     2.0     2.0
1         4.0     4.0     4.0     4.0     4.0     4.0     2.0     4.0
2         4.0     4.0     4.0     4.0     4.0     4.0     3.0     4.0
3         2.0     1.0     1.0     1.0     3.0     2.0     2.0     2.0
4         3.0     4.0     5.0     5.0     4.0     4.0     5.0     5.0
...       ...     ...     ...     ...     ...     ...     ...     ...
11105     5.0     5.0     5.0     5.0     5.0     5.0     5.0     5.0
11106     5.0     5.0     5.0     5.0     5.0     5.0     5.0     5.0
11107     3.0     3.0     3.0     3.0     3.0     3.0     3.0     3.0
11108     5.0     5.0     5.0     5.0     5.0     5.0     5.0     5.0
11109     4.0     4.0     4.0     4.0     4.0     4.0     4.0     4.0

[11110 rows x 8 columns]

In [54]:
name = 'NIHE'
input_vars = data.loc[:,'NIHE1_1':'NIHE1_8'].columns
validation, data = run_analysis(data, validation, name, input_vars)

  NIHE1_1 NIHE1_2 NIHE1_3 NIHE1_4 NIHE1_5 NIHE1_6 NIHE1_7 NIHE1_8
0     2.0     2.0     2.0     2.0     2.0     2.0     2.0     2.0
1     4.0     4.0     4.0     4.0     4.0     4.0     2.0     4.0
2     4.0     4.0     4.0     4.0     4.0     4.0     3.0     4.0
3     2.0     1.0     1.0     1.0     3.0     2.0     2.0     2.0
4     3.0     4.0     5.0     5.0     4.0     4.0     5.0     5.0
0                [8]
1          [6, 1, 1]
2          [6, 1, 1]
3       [1, 3, 1, 3]
4    [1, 1, 2, 2, 2]
dtype: object
   maxLongString_NIHE  meanLongString_NIHE  countLongString_NIHE
0                 8.0             8.000000                   1.0
1                 6.0             2.666667                   1.0
2                 6.0             2.666667                   1.0
3                 3.0             2.000000                   0.0
4                 2.0             1.600000                   0.0

In [55]:
name = 'NIHL'
input_vars = data.loc[:,'NIHL1_1':'NIHL1_5'].columns
validation, data = run_analysis(data, validation, name, input_vars)

  NIHL1_1 NIHL1_2 NIHL1_3 NIHL1_4 NIHL1_5
0     5.0     5.0     5.0     5.0     5.0
1     3.0     2.0     1.0     2.0     2.0
2     2.0     3.0     2.0     2.0     2.0
3     5.0     5.0     5.0     5.0     5.0
4     3.0     3.0     3.0     4.0     3.0
0             [5]
1    [1, 1, 1, 2]
2       [1, 1, 3]
3             [5]
4       [3, 1, 1]
dtype: object
   maxLongString_NIHL  meanLongString_NIHL  countLongString_NIHL
0                 5.0             5.000000                   1.0
1                 2.0             1.250000                   0.0
2                 3.0             1.666667                   0.0
3                 5.0             5.000000                   1.0
4                 3.0             1.666667                   0.0

In [56]:
name = 'BDI'
input_vars = data.loc[:,'BDI1':'BDI21'].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     BDI1 BDI2 BDI3 BDI4 BDI5 BDI6 BDI7 BDI8 BDI9 BDI10  ... BDI12 BDI13  \
7430  2.0  2.0  2.0  2.0  2.0  2.0  2.0  1.0  1.0   1.0  ...   1.0   1.0
7431  2.0  2.0  3.0  3.0  3.0  2.0  4.0  2.0  1.0   3.0  ...   2.0   2.0
7432  1.0  2.0  1.0  1.0  2.0  1.0  1.0  2.0  1.0   1.0  ...   1.0   2.0
7433  1.0  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0   1.0  ...   1.0   2.0
7434  2.0  3.0  2.0  2.0  2.0  2.0  1.0  2.0  2.0   2.0  ...   2.0   2.0

     BDI14 BDI15 BDI16 BDI17 BDI18 BDI19 BDI20 BDI21
7430   2.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0
7431   2.0   3.0   3.0   2.0   3.0   3.0   3.0   2.0
7432   2.0   1.0   1.0   2.0   1.0   2.0   1.0   1.0
7433   1.0   3.0   5.0   1.0   6.0   2.0   1.0   3.0
7434   2.0   2.0   2.0   2.0   3.0   2.0   2.0   2.0

[5 rows x 21 columns]
7430                                     [7, 6, 1, 7]
7431             [2, 3, 1, 1, 1, 1, 1, 4, 2, 1, 3, 1]
7432    [1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2]
7433             [3, 1, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1]
7434                           [1, 1, 4, 1, 10, 1, 3]
dtype: object
      maxLongString_BDI  meanLongString_BDI  countLongString_BDI
7430                7.0                5.25                  3.0
7431                4.0                1.75                  0.0
7432                2.0                1.40                  0.0
7433                8.0                1.75                  1.0
7434               10.0                3.00                  1.0

In [57]:
name = 'CD_RISK'
input_vars = data.loc[:,'RISC1_1':'RISC1_10'].columns
validation, data = run_analysis(data, validation, name, input_vars, '7')

     RISC1_1 RISC1_2 RISC1_3 RISC1_4 RISC1_5 RISC1_6 RISC1_7 RISC1_8 RISC1_9  \
8608     3.0     4.0     3.0     3.0     3.0     3.0     3.0     3.0     4.0
8609     5.0     5.0     5.0     4.0     5.0     4.0     5.0     5.0     5.0
8610     3.0     3.0     4.0     3.0     2.0     3.0     3.0     2.0     3.0
8611     4.0     4.0     4.0     4.0     4.0     4.0     4.0     4.0     4.0
8612     3.0     3.0     3.0     3.0     3.0     3.0     2.0     2.0     3.0

     RISC1_10
8608      4.0
8609      5.0
8610      4.0
8611      4.0
8612      3.0
8608                [1, 1, 6, 2]
8609             [3, 1, 1, 1, 4]
8610    [2, 1, 1, 1, 2, 1, 1, 1]
8611                        [10]
8612                   [6, 2, 2]
dtype: object
      maxLongString_CD_RISK  meanLongString_CD_RISK  countLongString_CD_RISK
8608                    6.0                2.500000                      1.0
8609                    4.0                2.000000                      0.0
8610                    2.0                1.250000                      0.0
8611                   10.0               10.000000                      1.0
8612                    6.0                3.333333                      1.0

In [58]:
name = 'consensBsl'
input_vars = data.loc[:, 'cons1_1':'cons1_35'].columns
validation, data = run_analysis(data, validation, name, input_vars, '5')

     cons1_1 cons1_2 cons1_3 cons1_4 cons1_5 cons1_6 cons1_7 cons1_8 cons1_9  \
6148     3.0     6.0     6.0     5.0     3.0     3.0     3.0     3.0     6.0
6149     2.0     6.0     4.0     4.0     4.0     6.0     6.0     6.0     7.0
6150     3.0     5.0     5.0     3.0     6.0     6.0     4.0     4.0     7.0
6151     6.0     8.0     7.0     6.0     5.0     6.0     7.0     7.0     8.0
6152     4.0     6.0     6.0     6.0     7.0     7.0     7.0     5.0     4.0

     cons1_10  ... cons1_26 cons1_27 cons1_28 cons1_29 cons1_30 cons1_31  \
6148      5.0  ...      2.0      2.0      3.0      3.0      1.0      7.0
6149      7.0  ...      3.0      3.0      3.0      3.0      5.0      3.0
6150      6.0  ...      3.0      3.0      3.0      3.0      4.0      3.0
6151      3.0  ...      4.0      3.0      5.0      4.0      5.0      4.0
6152      7.0  ...      3.0      3.0      4.0      3.0      3.0      3.0

     cons1_32 cons1_33 cons1_34 cons1_35
6148      7.0      6.0      6.0      5.0
6149      5.0      8.0      8.0      6.0
6150      3.0      3.0      5.0      4.0
6151      5.0      6.0      8.0      7.0
6152      4.0      6.0      8.0      8.0

[5 rows x 35 columns]
6148    [1, 2, 1, 4, 1, 1, 2, 1, 1, 1, 1, 1, 1, 4, 2, ...
6149    [1, 1, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, ...
6150    [1, 2, 1, 2, 2, 1, 1, 4, 1, 2, 1, 5, 1, 1, 4, ...
6151    [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 1, 1, 1, ...
6152    [1, 3, 3, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, ...
dtype: object
      maxLongString_consensBsl  meanLongString_consensBsl  \
6148                       4.0                   1.590909
6149                       4.0                   1.458333
6150                       5.0                   1.842105
6151                       3.0                   1.166667
6152                       3.0                   1.400000

      countLongString_consensBsl
6148                         0.0
6149                         0.0
6150                         1.0
6151                         0.0
6152                         0.0

In [59]:
name = "consensCvd"
input_vars = data.loc[:, 'cons2_1':'cons2_20'].columns
validation, data = run_analysis(data, validation, name, input_vars, '5')

     cons2_1 cons2_2 cons2_3 cons2_4 cons2_5 cons2_6 cons2_7 cons2_8 cons2_9  \
6148     6.0     2.0     1.0     7.0     9.0     1.0     1.0     6.0     3.0
6149     1.0     9.0     9.0     1.0     3.0     7.0     8.0     7.0     8.0
6150     7.0     4.0     5.0     3.0     7.0     5.0     7.0     7.0     7.0
6151     6.0     2.0     7.0     6.0     8.0     3.0     4.0     2.0     8.0
6152     8.0     3.0     6.0     8.0     9.0     1.0     1.0     7.0     7.0

     cons2_10 cons2_11 cons2_12 cons2_13 cons2_14 cons2_15 cons2_16 cons2_17  \
6148      6.0      1.0      5.0      1.0      1.0      2.0      6.0      3.0
6149      9.0      6.0      7.0      4.0      6.0      1.0      8.0      7.0
6150      6.0      6.0      2.0      3.0      7.0      3.0      7.0      7.0
6151      6.0      8.0      7.0      6.0      6.0      2.0      8.0      7.0
6152      6.0      7.0      7.0      3.0      7.0      1.0      9.0      3.0

     cons2_18 cons2_19 cons2_20
6148      1.0      3.0      1.0
6149      7.0      8.0      1.0
6150      6.0      7.0      7.0
6151      5.0      3.0      6.0
6152      1.0      1.0      2.0
6148    [1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, ...
6149    [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
6150        [1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 2, 1, 2]
6151    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, ...
6152     [1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1]
dtype: object
      maxLongString_consensCvd  meanLongString_consensCvd  \
6148                       2.0                   1.111111
6149                       2.0                   1.111111
6150                       3.0                   1.333333
6151                       2.0                   1.052632
6152                       2.0                   1.250000

      countLongString_consensCvd
6148                         0.0
6149                         0.0
6150                         0.0
6151                         0.0
6152                         0.0

In [60]:
name = 'EPII_infectHist_you'
input_vars = ["EPII10_1_1",  "EPII10_2_1", "EPII10_3_1",  "EPII10_4_1",  "EPII10_5_1",  'EPII10_6_1',  'EPII10_7_1',  'EPII10_8_1']

validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII10_1_1 EPII10_2_1 EPII10_3_1 EPII10_4_1 EPII10_5_1 EPII10_6_1  \
7430          0        NaN        1.0          0        1.0          0
7431        1.0        NaN          0          0        1.0        1.0
7432          0        NaN        1.0          0          0          0
7433          0        NaN          0          0          0          0
7434          0        NaN        1.0          0          0          0

     EPII10_7_1 EPII10_8_1
7430        1.0          0
7431          0        1.0
7432          0          0
7433          0          0
7434          0          0
7430    [1, 1, 1, 1, 1, 1]
7431          [2, 2, 1, 1]
7432                [1, 5]
7433                   [6]
7434                [1, 5]
dtype: object
      maxLongString_EPII_infectHist_you  meanLongString_EPII_infectHist_you  \
7430                                1.0                                 1.0
7431                                2.0                                 1.5
7432                                5.0                                 3.0
7433                                6.0                                 6.0
7434                                5.0                                 3.0

      countLongString_EPII_infectHist_you
7430                                  0.0
7431                                  0.0
7432                                  1.0
7433                                  1.0
7434                                  1.0

In [61]:
name = 'EPII_infectHist_inHome'
input_vars = ["EPII10_1_2", "EPII10_2_2", "EPII10_3_2", "EPII10_4_2", "EPII10_5_2", "EPII10_6_2", "EPII10_7_2", "EPII10_8_2"]
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII10_1_2 EPII10_2_2 EPII10_3_2 EPII10_4_2 EPII10_5_2 EPII10_6_2  \
7430          0        1.0          0        1.0          0        1.0
7431          0        1.0        1.0        1.0          0          0
7432          0          0          0          0          0          0
7433        1.0        1.0        1.0        1.0        1.0        1.0
7434          0          0        1.0          0          0          0

     EPII10_7_2 EPII10_8_2
7430          0          0
7431        1.0          0
7432        1.0          0
7433        1.0        1.0
7434          0          0
7430    [1, 1, 1, 1, 1, 1, 2]
7431          [1, 3, 2, 1, 1]
7432                [6, 1, 1]
7433                      [8]
7434                [2, 1, 5]
dtype: object
      maxLongString_EPII_infectHist_inHome  \
7430                                   2.0
7431                                   3.0
7432                                   6.0
7433                                   8.0
7434                                   5.0

      meanLongString_EPII_infectHist_inHome  \
7430                               1.142857
7431                               1.600000
7432                               2.666667
7433                               8.000000
7434                               2.666667

      countLongString_EPII_infectHist_inHome
7430                                     0.0
7431                                     0.0
7432                                     1.0
7433                                     1.0
7434                                     1.0

In [62]:
name = 'EPII_infectHist_no'
input_vars = ["EPII10_1_3",  "EPII10_2_3", "EPII10_3_3",  "EPII10_4_3",  "EPII10_5_3",  "EPII10_6_3",  "EPII10_7_3",  "EPII10_8_3" ]
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII10_1_3 EPII10_2_3 EPII10_3_3 EPII10_4_3 EPII10_5_3 EPII10_6_3  \
7430          0          0          0          0          0          0
7431          0          0          0          0          0          0
7432        1.0        1.0          0        1.0        1.0        1.0
7433          0          0          0          0          0          0
7434        1.0        1.0          0        1.0        1.0        1.0

     EPII10_7_3 EPII10_8_3
7430          0          0
7431          0          0
7432          0        1.0
7433          0          0
7434        1.0        1.0
7430                [8]
7431                [8]
7432    [2, 1, 3, 1, 1]
7433                [8]
7434          [2, 1, 5]
dtype: object
      maxLongString_EPII_infectHist_no  meanLongString_EPII_infectHist_no  \
7430                               8.0                           8.000000
7431                               8.0                           8.000000
7432                               3.0                           1.600000
7433                               8.0                           8.000000
7434                               5.0                           2.666667

      countLongString_EPII_infectHist_no
7430                                 1.0
7431                                 1.0
7432                                 0.0
7433                                 1.0
7434                                 1.0

In [63]:
name = 'EPII_infectHist_NA'
input_vars = ["EPII10_1_4",  "EPII10_2_4", "EPII10_3_4",  "EPII10_4_4",  "EPII10_5_4",  "EPII10_6_4",  "EPII10_7_4",  "EPII10_8_4"]
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII10_1_4 EPII10_2_4 EPII10_3_4 EPII10_4_4 EPII10_5_4 EPII10_6_4  \
7430          0          0          0          0          0          0
7431          0          0          0          0          0          0
7432          0          0          0          0          0          0
7433          0          0          0          0          0          0
7434          0          0          0          0          0          0

     EPII10_7_4 EPII10_8_4
7430          0          0
7431          0          0
7432          0          0
7433          0          0
7434          0          0
7430    [8]
7431    [8]
7432    [8]
7433    [8]
7434    [8]
dtype: object
      maxLongString_EPII_infectHist_NA  meanLongString_EPII_infectHist_NA  \
7430                               8.0                                8.0
7431                               8.0                                8.0
7432                               8.0                                8.0
7433                               8.0                                8.0
7434                               8.0                                8.0

      countLongString_EPII_infectHist_NA
7430                                 1.0
7431                                 1.0
7432                                 1.0
7433                                 1.0
7434                                 1.0

In [64]:
name = 'EPII_posChange_you'
input_vars = construct_vars('EPII11_', 18, '_1')
print(input_vars)
validation, data = run_analysis(data, validation, name, input_vars, '6')

['EPII11_1_1', 'EPII11_2_1', 'EPII11_3_1', 'EPII11_4_1', 'EPII11_5_1', 'EPII11_6_1', 'EPII11_7_1', 'EPII11_8_1', 'EPII11_9_1', 'EPII11_10_1', 'EPII11_11_1', 'EPII11_12_1', 'EPII11_13_1', 'EPII11_14_1', 'EPII11_15_1', 'EPII11_16_1', 'EPII11_17_1', 'EPII11_18_1']
     EPII11_1_1 EPII11_2_1 EPII11_3_1 EPII11_4_1 EPII11_5_1 EPII11_6_1  \
7430          0        1.0        1.0          0          0        1.0
7431        1.0          0        1.0        1.0        1.0          0
7432        1.0        1.0        1.0          0          0        1.0
7433          0          0          0          0          0          0
7434        1.0        1.0        1.0        1.0          0        1.0

     EPII11_7_1 EPII11_8_1 EPII11_9_1 EPII11_10_1 EPII11_11_1 EPII11_12_1  \
7430        1.0          0          0           0         1.0           0
7431        1.0        1.0          0         1.0           0         1.0
7432          0          0          0         1.0           0           0
7433          0          0          0           0           0           0
7434        1.0          0        1.0         1.0         1.0           0

     EPII11_13_1 EPII11_14_1 EPII11_15_1 EPII11_16_1 EPII11_17_1 EPII11_18_1
7430         1.0         1.0           0         1.0           0         1.0
7431         1.0           0         1.0         1.0         1.0         1.0
7432           0           0           0           0           0           0
7433           0           0           0           0           0           0
7434           0           0           0           0           0           0
7430    [1, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1, 1]
7431       [1, 1, 3, 1, 2, 1, 1, 1, 2, 1, 4]
7432                      [3, 2, 1, 3, 1, 8]
7433                                    [18]
7434                      [4, 1, 2, 1, 3, 7]
dtype: object
      maxLongString_EPII_posChange_you  meanLongString_EPII_posChange_you  \
7430                               3.0                           1.500000
7431                               4.0                           1.636364
7432                               8.0                           3.000000
7433                              18.0                          18.000000
7434                               7.0                           3.000000

      countLongString_EPII_posChange_you
7430                                 0.0
7431                                 0.0
7432                                 1.0
7433                                 1.0
7434                                 1.0

In [65]:
name = 'EPII_posChange_inHome'
input_vars = construct_vars('EPII11_', 18, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII11_1_2 EPII11_2_2 EPII11_3_2 EPII11_4_2 EPII11_5_2 EPII11_6_2  \
7430        1.0          0          0        1.0        1.0          0
7431        1.0        1.0        1.0        1.0        1.0        1.0
7432        1.0        1.0        1.0          0          0        1.0
7433        1.0        1.0        1.0        1.0        1.0        1.0
7434        1.0        1.0        1.0        1.0          0          0

     EPII11_7_2 EPII11_8_2 EPII11_9_2 EPII11_10_2 EPII11_11_2 EPII11_12_2  \
7430          0        1.0        1.0         1.0         1.0         1.0
7431          0          0        1.0         1.0         1.0           0
7432          0          0        1.0         1.0           0           0
7433        1.0        1.0        1.0         1.0         1.0         1.0
7434          0        1.0        1.0           0           0           0

     EPII11_13_2 EPII11_14_2 EPII11_15_2 EPII11_16_2 EPII11_17_2 EPII11_18_2
7430           0           0         1.0           0         1.0           0
7431           0         1.0         1.0         1.0           0         1.0
7432           0           0           0           0           0           0
7433         1.0         1.0         1.0         1.0         1.0         1.0
7434           0           0           0           0           0           0
7430    [1, 2, 2, 2, 5, 2, 1, 1, 1, 1]
7431             [6, 2, 3, 2, 3, 1, 1]
7432                [3, 2, 1, 2, 2, 8]
7433                              [18]
7434                      [4, 3, 2, 9]
dtype: object
      maxLongString_EPII_posChange_inHome  \
7430                                  5.0
7431                                  6.0
7432                                  8.0
7433                                 18.0
7434                                  9.0

      meanLongString_EPII_posChange_inHome  \
7430                              1.800000
7431                              2.571429
7432                              3.000000
7433                             18.000000
7434                              4.500000

      countLongString_EPII_posChange_inHome
7430                                    1.0
7431                                    1.0
7432                                    1.0
7433                                    1.0
7434                                    1.0

In [66]:
name = 'EPII_posChange_no'
input_vars = construct_vars('EPII11_', 18, '_3')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII11_1_3 EPII11_2_3 EPII11_3_3 EPII11_4_3 EPII11_5_3 EPII11_6_3  \
7430          0          0          0          0          0          0
7431          0          0          0          0          0          0
7432          0          0          0        1.0        1.0          0
7433          0          0          0          0          0          0
7434          0          0          0          0          0          0

     EPII11_7_3 EPII11_8_3 EPII11_9_3 EPII11_10_3 EPII11_11_3 EPII11_12_3  \
7430          0          0          0           0           0           0
7431          0          0          0           0           0           0
7432        1.0        1.0          0           0         1.0         1.0
7433          0          0          0           0           0           0
7434          0          0          0           0           0         1.0

     EPII11_13_3 EPII11_14_3 EPII11_15_3 EPII11_16_3 EPII11_17_3 EPII11_18_3
7430           0           0           0           0           0           0
7431           0           0           0           0           0           0
7432         1.0         1.0         1.0         1.0         1.0         1.0
7433           0           0           0           0           0           0
7434         1.0         1.0         1.0         1.0         1.0         1.0
7430                  [18]
7431                  [18]
7432    [3, 2, 1, 2, 2, 8]
7433                  [18]
7434               [11, 7]
dtype: object
      maxLongString_EPII_posChange_no  meanLongString_EPII_posChange_no  \
7430                             18.0                              18.0
7431                             18.0                              18.0
7432                              8.0                               3.0
7433                             18.0                              18.0
7434                             11.0                               9.0

      countLongString_EPII_posChange_no
7430                                1.0
7431                                1.0
7432                                1.0
7433                                1.0
7434                                2.0

In [67]:
name = 'EPII_posChange_NA'
input_vars = construct_vars('EPII11_', 18, '_4')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII11_1_4 EPII11_2_4 EPII11_3_4 EPII11_4_4 EPII11_5_4 EPII11_6_4  \
7430          0          0          0          0          0          0
7431          0          0          0          0          0          0
7432          0          0          0          0          0          0
7433          0          0          0          0          0          0
7434          0          0          0          0          0          0

     EPII11_7_4 EPII11_8_4 EPII11_9_4 EPII11_10_4 EPII11_11_4 EPII11_12_4  \
7430          0          0          0           0           0           0
7431          0          0          0           0           0           0
7432          0          0          0           0           0           0
7433          0          0          0           0           0           0
7434          0          0          0           0           0           0

     EPII11_13_4 EPII11_14_4 EPII11_15_4 EPII11_16_4 EPII11_17_4 EPII11_18_4
7430           0           0           0           0           0           0
7431           0           0           0           0           0           0
7432           0           0           0           0           0           0
7433           0           0           0           0           0           0
7434           0           0           0           0           0           0
7430    [18]
7431    [18]
7432    [18]
7433    [18]
7434    [18]
dtype: object
      maxLongString_EPII_posChange_NA  meanLongString_EPII_posChange_NA  \
7430                             18.0                              18.0
7431                             18.0                              18.0
7432                             18.0                              18.0
7433                             18.0                              18.0
7434                             18.0                              18.0

      countLongString_EPII_posChange_NA
7430                                1.0
7431                                1.0
7432                                1.0
7433                                1.0
7434                                1.0

In [68]:
name = 'EPII_work_you'
input_vars = construct_vars('EPII2_', 11, '_1')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII2_1_1 EPII2_2_1 EPII2_3_1 EPII2_4_1 EPII2_5_1 EPII2_6_1 EPII2_7_1  \
7430         0         0         0         0       1.0       1.0         0
7431       1.0       1.0         0       1.0       1.0         0         0
7432         0         0       1.0         0         0       1.0         0
7433         0         0         0         0         0         0         0
7434       1.0         0         0       1.0       1.0         0         0

     EPII2_8_1 EPII2_9_1 EPII2_10_1 EPII2_11_1
7430       1.0         0          0          0
7431       1.0       1.0          0          0
7432         0         0          0          0
7433         0         0          0          0
7434         0         0          0          0
7430       [4, 2, 1, 1, 3]
7431    [2, 1, 2, 2, 2, 2]
7432       [2, 1, 2, 1, 5]
7433                  [11]
7434          [1, 2, 2, 6]
dtype: object
      maxLongString_EPII_work_you  meanLongString_EPII_work_you  \
7430                          4.0                      2.200000
7431                          2.0                      1.833333
7432                          5.0                      2.200000
7433                         11.0                     11.000000
7434                          6.0                      2.750000

      countLongString_EPII_work_you
7430                            0.0
7431                            0.0
7432                            1.0
7433                            1.0
7434                            1.0

In [69]:
name = 'EPII_work_inHome'
input_vars = construct_vars('EPII2_', 11, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII2_1_2 EPII2_2_2 EPII2_3_2 EPII2_4_2 EPII2_5_2 EPII2_6_2 EPII2_7_2  \
7430         0         0         0         0         0         0       1.0
7431       1.0         0         0         0         0         0       1.0
7432         0         0         0         0         0         0         0
7433       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7434       1.0         0         0       1.0       1.0       1.0         0

     EPII2_8_2 EPII2_9_2 EPII2_10_2 EPII2_11_2
7430         0         0          0          0
7431         0         0        1.0          0
7432         0         0          0          0
7433       1.0       1.0        1.0        1.0
7434         0         0          0          0
7430             [6, 1, 4]
7431    [1, 5, 1, 2, 1, 1]
7432                  [11]
7433                  [11]
7434          [1, 2, 3, 5]
dtype: object
      maxLongString_EPII_work_inHome  meanLongString_EPII_work_inHome  \
7430                             6.0                         3.666667
7431                             5.0                         1.833333
7432                            11.0                        11.000000
7433                            11.0                        11.000000
7434                             5.0                         2.750000

      countLongString_EPII_work_inHome
7430                               1.0
7431                               1.0
7432                               1.0
7433                               1.0
7434                               1.0

In [70]:
name = 'EPII_work_no'
input_vars = construct_vars('EPII2_', 11, '_4')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII2_1_4 EPII2_2_4 EPII2_3_4 EPII2_4_4 EPII2_5_4 EPII2_6_4 EPII2_7_4  \
7430       1.0       1.0       1.0       1.0         0         0         0
7431         0         0       1.0         0         0       1.0         0
7432       1.0       1.0         0       1.0       1.0         0       1.0
7433         0         0         0         0         0         0         0
7434         0       1.0       1.0         0         0         0       1.0

     EPII2_8_4 EPII2_9_4 EPII2_10_4 EPII2_11_4
7430         0       1.0        1.0        1.0
7431         0         0          0        1.0
7432       1.0       1.0        1.0        1.0
7433         0         0          0          0
7434       1.0       1.0        1.0        1.0
7430             [4, 4, 3]
7431    [2, 1, 2, 1, 4, 1]
7432       [2, 1, 2, 1, 5]
7433                  [11]
7434          [1, 2, 3, 5]
dtype: object
      maxLongString_EPII_work_no  meanLongString_EPII_work_no  \
7430                         4.0                     3.666667
7431                         4.0                     1.833333
7432                         5.0                     2.200000
7433                        11.0                    11.000000
7434                         5.0                     2.750000

      countLongString_EPII_work_no
7430                           0.0
7431                           0.0
7432                           1.0
7433                           1.0
7434                           1.0

In [71]:
name = 'EPII_work_NA'
input_vars = construct_vars('EPII2_', 11, '_5')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII2_1_5 EPII2_2_5 EPII2_3_5 EPII2_4_5 EPII2_5_5 EPII2_6_5 EPII2_7_5  \
7430         0         0         0         0         0         0         0
7431         0         0         0         0         0         0         0
7432         0         0         0         0         0         0         0
7433         0         0         0         0         0         0         0
7434         0         0         0         0         0         0         0

     EPII2_8_5 EPII2_9_5 EPII2_10_5 EPII2_11_5
7430         0         0          0          0
7431         0         0          0          0
7432         0         0          0          0
7433         0         0          0          0
7434         0         0          0          0
7430    [11]
7431    [11]
7432    [11]
7433    [11]
7434    [11]
dtype: object
      maxLongString_EPII_work_NA  meanLongString_EPII_work_NA  \
7430                        11.0                         11.0
7431                        11.0                         11.0
7432                        11.0                         11.0
7433                        11.0                         11.0
7434                        11.0                         11.0

      countLongString_EPII_work_NA
7430                           1.0
7431                           1.0
7432                           1.0
7433                           1.0
7434                           1.0

In [72]:
input_vars

['EPII2_1_5',
 'EPII2_2_5',
 'EPII2_3_5',
 'EPII2_4_5',
 'EPII2_5_5',
 'EPII2_6_5',
 'EPII2_7_5',
 'EPII2_8_5',
 'EPII2_9_5',
 'EPII2_10_5',
 'EPII2_11_5']

In [73]:
name = 'EPII_home_you'
input_vars = construct_vars('EPII4_', 13, '_1')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII4_1_1 EPII4_2_1 EPII4_3_1 EPII4_4_1 EPII4_5_1 EPII4_6_1 EPII4_7_1  \
7430         0         0         0         0         0         0         0
7431       1.0       1.0       1.0         0       1.0       1.0       1.0
7432         0         0         0         0         0         0         0
7433         0         0         0         0         0         0         0
7434       1.0       1.0       1.0         0         0       1.0         0

     EPII4_8_1 EPII4_9_1 EPII4_10_1 EPII4_11_1 EPII4_12_1 EPII4_13_1
7430         0         0          0          0          0          0
7431       1.0         0        1.0        1.0          0        1.0
7432         0         0          0          0          0          0
7433         0         0          0          0          0          0
7434         0       1.0          0        1.0          0          0
7430                        [13]
7431       [3, 1, 4, 1, 2, 1, 1]
7432                        [13]
7433                        [13]
7434    [3, 2, 1, 2, 1, 1, 1, 2]
dtype: object
      maxLongString_EPII_home_you  meanLongString_EPII_home_you  \
7430                         13.0                     13.000000
7431                          4.0                      1.857143
7432                         13.0                     13.000000
7433                         13.0                     13.000000
7434                          3.0                      1.625000

      countLongString_EPII_home_you
7430                            1.0
7431                            0.0
7432                            1.0
7433                            1.0
7434                            0.0

In [74]:
name = 'EPII_home_inHome'
input_vars = construct_vars('EPII4_', 13, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII4_1_2 EPII4_2_2 EPII4_3_2 EPII4_4_2 EPII4_5_2 EPII4_6_2 EPII4_7_2  \
7430         0         0         0         0         0         0         0
7431       1.0       1.0       1.0       1.0       1.0       1.0         0
7432         0         0         0         0         0         0         0
7433       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7434       1.0       1.0       1.0         0         0       1.0         0

     EPII4_8_2 EPII4_9_2 EPII4_10_2 EPII4_11_2 EPII4_12_2 EPII4_13_2
7430         0         0          0          0          0          0
7431         0       1.0        1.0        1.0        1.0          0
7432         0         0          0          0          0          0
7433       1.0       1.0        1.0        1.0        1.0        1.0
7434         0       1.0          0        1.0          0          0
7430                        [13]
7431                [6, 2, 4, 1]
7432                        [13]
7433                        [13]
7434    [3, 2, 1, 2, 1, 1, 1, 2]
dtype: object
      maxLongString_EPII_home_inHome  meanLongString_EPII_home_inHome  \
7430                            13.0                           13.000
7431                             6.0                            3.250
7432                            13.0                           13.000
7433                            13.0                           13.000
7434                             3.0                            1.625

      countLongString_EPII_home_inHome
7430                               1.0
7431                               1.0
7432                               1.0
7433                               1.0
7434                               0.0

In [75]:
name = 'EPII_home_no'
input_vars = construct_vars('EPII4_', 13, '_3')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII4_1_3 EPII4_2_3 EPII4_3_3 EPII4_4_3 EPII4_5_3 EPII4_6_3 EPII4_7_3  \
7430       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7431         0         0         0         0         0         0         0
7432       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7433         0         0         0         0         0         0         0
7434         0         0         0         0         0         0         0

     EPII4_8_3 EPII4_9_3 EPII4_10_3 EPII4_11_3 EPII4_12_3 EPII4_13_3
7430       1.0       1.0        1.0        1.0        1.0        1.0
7431         0         0          0          0          0          0
7432       1.0       1.0        1.0        1.0        1.0        1.0
7433         0         0          0          0          0          0
7434         0         0          0          0          0          0
7430    [13]
7431    [13]
7432    [13]
7433    [13]
7434    [13]
dtype: object
      maxLongString_EPII_home_no  meanLongString_EPII_home_no  \
7430                        13.0                         13.0
7431                        13.0                         13.0
7432                        13.0                         13.0
7433                        13.0                         13.0
7434                        13.0                         13.0

      countLongString_EPII_home_no
7430                           1.0
7431                           1.0
7432                           1.0
7433                           1.0
7434                           1.0

In [76]:
name = 'EPII_socAct_you'
input_vars = construct_vars('EPII5_', 10, '_1')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII5_1_1 EPII5_2_1 EPII5_3_1 EPII5_4_1 EPII5_5_1 EPII5_6_1 EPII5_7_1  \
7430       1.0         0       1.0       1.0       1.0         0         0
7431       1.0         0       1.0         0         0       1.0       1.0
7432         0         0         0       1.0       1.0         0         0
7433         0         0         0         0         0       1.0       1.0
7434       1.0         0       1.0       1.0       1.0         0         0

     EPII5_8_1 EPII5_9_1 EPII5_10_1
7430       1.0       1.0        1.0
7431       1.0       1.0        1.0
7432       1.0         0        1.0
7433       1.0         0          0
7434       1.0         0        1.0
7430          [1, 1, 3, 2, 3]
7431          [1, 1, 1, 2, 5]
7432       [3, 2, 2, 1, 1, 1]
7433                [5, 3, 2]
7434    [1, 1, 3, 2, 1, 1, 1]
dtype: object
      maxLongString_EPII_socAct_you  meanLongString_EPII_socAct_you  \
7430                            3.0                        2.000000
7431                            5.0                        2.000000
7432                            3.0                        1.666667
7433                            5.0                        3.333333
7434                            3.0                        1.428571

      countLongString_EPII_socAct_you
7430                              0.0
7431                              1.0
7432                              0.0
7433                              1.0
7434                              0.0

In [77]:
name = 'EPII_socAct_inHome'
input_vars = construct_vars('EPII5_', 10, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII5_1_2 EPII5_2_2 EPII5_3_2 EPII5_4_2 EPII5_5_2 EPII5_6_2 EPII5_7_2  \
7430       1.0         0         0       1.0       1.0       1.0       1.0
7431       1.0       1.0         0         0       1.0         0       1.0
7432         0         0         0         0         0         0         0
7433       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7434       1.0         0       1.0       1.0       1.0         0         0

     EPII5_8_2 EPII5_9_2 EPII5_10_2
7430       1.0         0          0
7431       1.0         0        1.0
7432         0         0          0
7433       1.0       1.0        1.0
7434         0       1.0        1.0
7430             [1, 2, 5, 2]
7431    [2, 2, 1, 1, 2, 1, 1]
7432                     [10]
7433                     [10]
7434          [1, 1, 3, 3, 2]
dtype: object
      maxLongString_EPII_socAct_inHome  meanLongString_EPII_socAct_inHome  \
7430                               5.0                           2.500000
7431                               2.0                           1.428571
7432                              10.0                          10.000000
7433                              10.0                          10.000000
7434                               3.0                           2.000000

      countLongString_EPII_socAct_inHome
7430                                 1.0
7431                                 0.0
7432                                 1.0
7433                                 1.0
7434                                 0.0

In [78]:
name = 'EPII_socAct_no'
input_vars = construct_vars('EPII5_', 10, '_3')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII5_1_3 EPII5_2_3 EPII5_3_3 EPII5_4_3 EPII5_5_3 EPII5_6_3 EPII5_7_3  \
7430         0       1.0         0         0         0         0         0
7431         0         0         0         0         0         0         0
7432       1.0       1.0       1.0         0         0       1.0       1.0
7433         0         0         0         0         0         0         0
7434         0       1.0         0         0         0       1.0       1.0

     EPII5_8_3 EPII5_9_3 EPII5_10_3
7430         0         0          0
7431         0         0          0
7432         0       1.0          0
7433         0         0          0
7434         0         0          0
7430             [1, 1, 8]
7431                  [10]
7432    [3, 2, 2, 1, 1, 1]
7433                  [10]
7434       [1, 1, 3, 2, 3]
dtype: object
      maxLongString_EPII_socAct_no  meanLongString_EPII_socAct_no  \
7430                           8.0                       3.333333
7431                          10.0                      10.000000
7432                           3.0                       1.666667
7433                          10.0                      10.000000
7434                           3.0                       2.000000

      countLongString_EPII_socAct_no
7430                             1.0
7431                             1.0
7432                             0.0
7433                             1.0
7434                             0.0

In [79]:
name = 'EPII_socAct_NA'
input_vars = construct_vars('EPII5_', 10, '_4')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII5_1_4 EPII5_2_4 EPII5_3_4 EPII5_4_4 EPII5_5_4 EPII5_6_4 EPII5_7_4  \
7430         0         0         0         0         0         0         0
7431         0         0         0         0         0         0         0
7432         0         0         0         0         0         0         0
7433         0         0         0         0         0         0         0
7434         0         0         0         0         0         0         0

     EPII5_8_4 EPII5_9_4 EPII5_10_4
7430         0         0          0
7431         0         0          0
7432         0         0          0
7433         0         0          0
7434         0         0          0
7430    [10]
7431    [10]
7432    [10]
7433    [10]
7434    [10]
dtype: object
      maxLongString_EPII_socAct_NA  meanLongString_EPII_socAct_NA  \
7430                          10.0                           10.0
7431                          10.0                           10.0
7432                          10.0                           10.0
7433                          10.0                           10.0
7434                          10.0                           10.0

      countLongString_EPII_socAct_NA
7430                             1.0
7431                             1.0
7432                             1.0
7433                             1.0
7434                             1.0

In [80]:
name = 'EPII_econ_you'
input_vars = construct_vars('EPII6_', 5, '_1')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII6_1_1 EPII6_2_1 EPII6_3_1 EPII6_4_1 EPII6_5_1
7430         0         0         0         0         0
7431       1.0         0       1.0       1.0       1.0
7432         0         0         0         0         0
7433         0         0         0         0         0
7434         0         0       1.0         0         0
7430          [5]
7431    [1, 1, 3]
7432          [5]
7433          [5]
7434    [2, 1, 2]
dtype: object
      maxLongString_EPII_econ_you  meanLongString_EPII_econ_you  \
7430                          5.0                      5.000000
7431                          3.0                      1.666667
7432                          5.0                      5.000000
7433                          5.0                      5.000000
7434                          2.0                      1.666667

      countLongString_EPII_econ_you
7430                            1.0
7431                            0.0
7432                            1.0
7433                            1.0
7434                            0.0

In [81]:
name = 'EPII_econ_inHome'
input_vars = construct_vars('EPII6_', 5, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII6_1_2 EPII6_2_2 EPII6_3_2 EPII6_4_2 EPII6_5_2
7430         0         0         0         0         0
7431         0       1.0         0       1.0       1.0
7432         0         0         0         0         0
7433       1.0       1.0       1.0       1.0       1.0
7434         0         0       1.0         0         0
7430             [5]
7431    [1, 1, 1, 2]
7432             [5]
7433             [5]
7434       [2, 1, 2]
dtype: object
      maxLongString_EPII_econ_inHome  meanLongString_EPII_econ_inHome  \
7430                             5.0                         5.000000
7431                             2.0                         1.250000
7432                             5.0                         5.000000
7433                             5.0                         5.000000
7434                             2.0                         1.666667

      countLongString_EPII_econ_inHome
7430                               1.0
7431                               0.0
7432                               1.0
7433                               1.0
7434                               0.0

In [82]:
name = 'EPII_econ_no'
input_vars = construct_vars('EPII6_', 5, '_3')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII6_1_3 EPII6_2_3 EPII6_3_3 EPII6_4_3 EPII6_5_3
7430       1.0       1.0       1.0       1.0       1.0
7431         0         0         0         0         0
7432       1.0       1.0       1.0       1.0       1.0
7433         0         0         0         0         0
7434       1.0       1.0         0       1.0       1.0
7430          [5]
7431          [5]
7432          [5]
7433          [5]
7434    [2, 1, 2]
dtype: object
      maxLongString_EPII_econ_no  meanLongString_EPII_econ_no  \
7430                         5.0                     5.000000
7431                         5.0                     5.000000
7432                         5.0                     5.000000
7433                         5.0                     5.000000
7434                         2.0                     1.666667

      countLongString_EPII_econ_no
7430                           1.0
7431                           1.0
7432                           1.0
7433                           1.0
7434                           0.0

In [83]:
name = 'EPII_econ_NA'
input_vars = construct_vars('EPII6_', 5, '_4')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII6_1_4 EPII6_2_4 EPII6_3_4 EPII6_4_4 EPII6_5_4
7430         0         0         0         0         0
7431         0         0         0         0         0
7432         0         0         0         0         0
7433         0         0         0         0         0
7434         0         0         0         0         0
7430    [5]
7431    [5]
7432    [5]
7433    [5]
7434    [5]
dtype: object
      maxLongString_EPII_econ_NA  meanLongString_EPII_econ_NA  \
7430                         5.0                          5.0
7431                         5.0                          5.0
7432                         5.0                          5.0
7433                         5.0                          5.0
7434                         5.0                          5.0

      countLongString_EPII_econ_NA
7430                           1.0
7431                           1.0
7432                           1.0
7433                           1.0
7434                           1.0

In [84]:
name = 'EPII_emo_you'
input_vars = construct_vars('EPII7_', 8, '_1')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII7_1_1 EPII7_2_1 EPII7_3_1 EPII7_4_1 EPII7_5_1 EPII7_6_1 EPII7_7_1  \
7430         0         0         0         0         0         0         0
7431       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7432         0         0       1.0         0       1.0         0         0
7433         0         0         0         0         0         0         0
7434       1.0       1.0       1.0       1.0       1.0         0         0

     EPII7_8_1
7430         0
7431       1.0
7432       1.0
7433         0
7434       1.0
7430                   [8]
7431                   [8]
7432    [2, 1, 1, 1, 2, 1]
7433                   [8]
7434             [5, 2, 1]
dtype: object
      maxLongString_EPII_emo_you  meanLongString_EPII_emo_you  \
7430                         8.0                     8.000000
7431                         8.0                     8.000000
7432                         2.0                     1.333333
7433                         8.0                     8.000000
7434                         5.0                     2.666667

      countLongString_EPII_emo_you
7430                           1.0
7431                           1.0
7432                           0.0
7433                           1.0
7434                           1.0

In [85]:
name = 'EPII_emo_inHome'
input_vars = construct_vars('EPII7_', 8, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII7_1_2 EPII7_2_2 EPII7_3_2 EPII7_4_2 EPII7_5_2 EPII7_6_2 EPII7_7_2  \
7430         0         0         0         0         0         0         0
7431       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7432         0         0         0       1.0         0       1.0         0
7433       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7434       1.0       1.0       1.0       1.0       1.0         0         0

     EPII7_8_2
7430         0
7431       1.0
7432       1.0
7433       1.0
7434       1.0
7430                   [8]
7431                   [8]
7432    [3, 1, 1, 1, 1, 1]
7433                   [8]
7434             [5, 2, 1]
dtype: object
      maxLongString_EPII_emo_inHome  meanLongString_EPII_emo_inHome  \
7430                            8.0                        8.000000
7431                            8.0                        8.000000
7432                            3.0                        1.333333
7433                            8.0                        8.000000
7434                            5.0                        2.666667

      countLongString_EPII_emo_inHome
7430                              1.0
7431                              1.0
7432                              0.0
7433                              1.0
7434                              1.0

In [86]:
name = 'EPII_emo_no'
input_vars = construct_vars('EPII7_', 8, '_3')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII7_1_3 EPII7_2_3 EPII7_3_3 EPII7_4_3 EPII7_5_3 EPII7_6_3 EPII7_7_3  \
7430       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7431         0         0         0         0         0         0         0
7432       1.0       1.0         0         0         0         0       1.0
7433         0         0         0         0         0         0         0
7434         0         0         0         0         0       1.0       1.0

     EPII7_8_3
7430       1.0
7431         0
7432         0
7433         0
7434         0
7430             [8]
7431             [8]
7432    [2, 4, 1, 1]
7433             [8]
7434       [5, 2, 1]
dtype: object
      maxLongString_EPII_emo_no  meanLongString_EPII_emo_no  \
7430                        8.0                    8.000000
7431                        8.0                    8.000000
7432                        4.0                    2.000000
7433                        8.0                    8.000000
7434                        5.0                    2.666667

      countLongString_EPII_emo_no
7430                          1.0
7431                          1.0
7432                          0.0
7433                          1.0
7434                          1.0

In [87]:
name = 'EPII_emo_NA'
input_vars = construct_vars('EPII7_', 8, '_4')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII7_1_4 EPII7_2_4 EPII7_3_4 EPII7_4_4 EPII7_5_4 EPII7_6_4 EPII7_7_4  \
7430         0         0         0         0         0         0         0
7431         0         0         0         0         0         0         0
7432         0         0         0         0         0         0         0
7433         0         0         0         0         0         0         0
7434         0         0         0         0         0         0         0

     EPII7_8_4
7430         0
7431         0
7432         0
7433         0
7434         0
7430    [8]
7431    [8]
7432    [8]
7433    [8]
7434    [8]
dtype: object
      maxLongString_EPII_emo_NA  meanLongString_EPII_emo_NA  \
7430                        8.0                         8.0
7431                        8.0                         8.0
7432                        8.0                         8.0
7433                        8.0                         8.0
7434                        8.0                         8.0

      countLongString_EPII_emo_NA
7430                          1.0
7431                          1.0
7432                          1.0
7433                          1.0
7434                          1.0

In [88]:
name = 'EPII_phys_you'
input_vars = construct_vars('EPII8_', 8, '_1')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII8_1_1 EPII8_2_1 EPII8_3_1 EPII8_4_1 EPII8_5_1 EPII8_6_1 EPII8_7_1  \
7430         0         0       1.0       1.0         0       1.0         0
7431       1.0         0       1.0       1.0         0         0       1.0
7432         0         0       1.0       1.0         0         0         0
7433         0         0         0         0         0         0         0
7434         0         0         0         0         0         0         0

     EPII8_8_1
7430       1.0
7431       1.0
7432         0
7433         0
7434         0
7430    [2, 2, 1, 1, 1, 1]
7431       [1, 1, 2, 2, 2]
7432             [2, 2, 4]
7433                   [8]
7434                   [8]
dtype: object
      maxLongString_EPII_phys_you  meanLongString_EPII_phys_you  \
7430                          2.0                      1.333333
7431                          2.0                      1.600000
7432                          4.0                      2.666667
7433                          8.0                      8.000000
7434                          8.0                      8.000000

      countLongString_EPII_phys_you
7430                            0.0
7431                            0.0
7432                            0.0
7433                            1.0
7434                            1.0

In [89]:
name = 'EPII_phys_inHome'
input_vars = construct_vars('EPII8_', 8, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII8_1_2 EPII8_2_2 EPII8_3_2 EPII8_4_2 EPII8_5_2 EPII8_6_2 EPII8_7_2  \
7430       1.0       1.0         0         0       1.0         0       1.0
7431       1.0       1.0         0       1.0         0       1.0       1.0
7432         0         0       1.0       1.0         0         0         0
7433       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7434         0         0       1.0       1.0         0         0         0

     EPII8_8_2
7430         0
7431       1.0
7432         0
7433       1.0
7434         0
7430    [2, 2, 1, 1, 1, 1]
7431       [2, 1, 1, 1, 3]
7432             [2, 2, 4]
7433                   [8]
7434             [2, 2, 4]
dtype: object
      maxLongString_EPII_phys_inHome  meanLongString_EPII_phys_inHome  \
7430                             2.0                         1.333333
7431                             3.0                         1.600000
7432                             4.0                         2.666667
7433                             8.0                         8.000000
7434                             4.0                         2.666667

      countLongString_EPII_phys_inHome
7430                               0.0
7431                               0.0
7432                               0.0
7433                               1.0
7434                               0.0

In [90]:
name = 'EPII_phys_no'
input_vars = construct_vars('EPII8_', 8, '_3')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII8_1_3 EPII8_2_3 EPII8_3_3 EPII8_4_3 EPII8_5_3 EPII8_6_3 EPII8_7_3  \
7430         0         0         0         0         0         0         0
7431         0         0         0         0       1.0         0         0
7432       1.0       1.0         0         0       1.0       1.0       1.0
7433         0         0         0         0         0         0         0
7434       1.0       1.0         0         0       1.0       1.0       1.0

     EPII8_8_3
7430         0
7431         0
7432       1.0
7433         0
7434       1.0
7430          [8]
7431    [4, 1, 3]
7432    [2, 2, 4]
7433          [8]
7434    [2, 2, 4]
dtype: object
      maxLongString_EPII_phys_no  meanLongString_EPII_phys_no  \
7430                         8.0                     8.000000
7431                         4.0                     2.666667
7432                         4.0                     2.666667
7433                         8.0                     8.000000
7434                         4.0                     2.666667

      countLongString_EPII_phys_no
7430                           1.0
7431                           0.0
7432                           0.0
7433                           1.0
7434                           0.0

In [91]:
name = 'EPII_phys_NA'
input_vars = construct_vars('EPII8_', 8, '_4')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII8_1_4 EPII8_2_4 EPII8_3_4 EPII8_4_4 EPII8_5_4 EPII8_6_4 EPII8_7_4  \
7430         0         0         0         0         0         0         0
7431         0         0         0         0         0         0         0
7432         0         0         0         0         0         0         0
7433         0         0         0         0         0         0         0
7434         0         0         0         0         0         0         0

     EPII8_8_4
7430         0
7431         0
7432         0
7433         0
7434         0
7430    [8]
7431    [8]
7432    [8]
7433    [8]
7434    [8]
dtype: object
      maxLongString_EPII_phys_NA  meanLongString_EPII_phys_NA  \
7430                         8.0                          8.0
7431                         8.0                          8.0
7432                         8.0                          8.0
7433                         8.0                          8.0
7434                         8.0                          8.0

      countLongString_EPII_phys_NA
7430                           1.0
7431                           1.0
7432                           1.0
7433                           1.0
7434                           1.0

In [92]:
name = 'EPII_dist_you'
input_vars = construct_vars('EPII9_', 8, '_1')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII9_1_1 EPII9_2_1 EPII9_3_1 EPII9_4_1 EPII9_5_1 EPII9_6_1 EPII9_7_1  \
7430         0         0       1.0       1.0       1.0         0       1.0
7431       1.0       1.0       1.0         0       1.0         0         0
7432         0       1.0         0         0         0         0         0
7433         0         0         0         0         0         0         0
7434       1.0         0       1.0       1.0         0         0         0

     EPII9_8_1
7430       1.0
7431       1.0
7432         0
7433         0
7434       1.0
7430       [2, 3, 1, 2]
7431    [3, 1, 1, 2, 1]
7432          [1, 1, 6]
7433                [8]
7434    [1, 1, 2, 3, 1]
dtype: object
      maxLongString_EPII_dist_you  meanLongString_EPII_dist_you  \
7430                          3.0                      2.000000
7431                          3.0                      1.600000
7432                          6.0                      2.666667
7433                          8.0                      8.000000
7434                          3.0                      1.600000

      countLongString_EPII_dist_you
7430                            0.0
7431                            0.0
7432                            1.0
7433                            1.0
7434                            0.0

In [93]:
name = 'EPII_dist_inHome'
input_vars = construct_vars('EPII9_', 8, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII9_1_2 EPII9_2_2 EPII9_3_2 EPII9_4_2 EPII9_5_2 EPII9_6_2 EPII9_7_2  \
7430       1.0       1.0       1.0         0         0       1.0       1.0
7431         0       1.0         0       1.0         0       1.0       1.0
7432         0         0         0         0         0         0         0
7433       1.0       1.0       1.0       1.0       1.0       1.0       1.0
7434       1.0         0       1.0       1.0         0         0         0

     EPII9_8_2
7430       1.0
7431         0
7432         0
7433       1.0
7434       1.0
7430                [3, 2, 3]
7431    [1, 1, 1, 1, 1, 2, 1]
7432                      [8]
7433                      [8]
7434          [1, 1, 2, 3, 1]
dtype: object
      maxLongString_EPII_dist_inHome  meanLongString_EPII_dist_inHome  \
7430                             3.0                         2.666667
7431                             2.0                         1.142857
7432                             8.0                         8.000000
7433                             8.0                         8.000000
7434                             3.0                         1.600000

      countLongString_EPII_dist_inHome
7430                               0.0
7431                               0.0
7432                               1.0
7433                               1.0
7434                               0.0

In [94]:
name = 'EPII_dist_no'
input_vars = construct_vars('EPII9_', 8, '_3')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII9_1_3 EPII9_2_3 EPII9_3_3 EPII9_4_3 EPII9_5_3 EPII9_6_3 EPII9_7_3  \
7430         0         0         0         0         0         0         0
7431         0         0         0         0         0         0         0
7432       1.0         0       1.0       1.0       1.0       1.0       1.0
7433         0         0         0         0         0         0         0
7434         0       1.0         0         0       1.0       1.0       1.0

     EPII9_8_3
7430         0
7431         0
7432       1.0
7433         0
7434         0
7430                [8]
7431                [8]
7432          [1, 1, 6]
7433                [8]
7434    [1, 1, 2, 3, 1]
dtype: object
      maxLongString_EPII_dist_no  meanLongString_EPII_dist_no  \
7430                         8.0                     8.000000
7431                         8.0                     8.000000
7432                         6.0                     2.666667
7433                         8.0                     8.000000
7434                         3.0                     1.600000

      countLongString_EPII_dist_no
7430                           1.0
7431                           1.0
7432                           1.0
7433                           1.0
7434                           0.0

In [95]:
name = 'EPII_dist_NA'
input_vars = construct_vars('EPII9_', 8, '_4')
validation, data = run_analysis(data, validation, name, input_vars, '6')

     EPII9_1_4 EPII9_2_4 EPII9_3_4 EPII9_4_4 EPII9_5_4 EPII9_6_4 EPII9_7_4  \
7430         0         0         0         0         0         0         0
7431         0         0         0         0         0         0         0
7432         0         0         0         0         0         0         0
7433         0         0         0         0         0         0         0
7434         0         0         0         0         0         0         0

     EPII9_8_4
7430         0
7431         0
7432         0
7433         0
7434         0
7430    [8]
7431    [8]
7432    [8]
7433    [8]
7434    [8]
dtype: object
      maxLongString_EPII_dist_NA  meanLongString_EPII_dist_NA  \
7430                         8.0                          8.0
7431                         8.0                          8.0
7432                         8.0                          8.0
7433                         8.0                          8.0
7434                         8.0                          8.0

      countLongString_EPII_dist_NA
7430                           1.0
7431                           1.0
7432                           1.0
7433                           1.0
7434                           1.0

In [96]:
name = 'trustPolit'
input_vars = data.loc[:, "RW6_1_1":"RW6_1_11"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW6_1_1 RW6_1_2 RW6_1_3 RW6_1_4 RW6_1_5 RW6_1_6 RW6_1_8 RW6_1_9 RW6_1_10  \
7430     3.0     1.0     3.0     5.0     3.0     3.0     3.0     3.0      3.0
7431     3.0     2.0     3.0     3.0     2.0     2.0     2.0     2.0      3.0
7432     4.0     2.0     4.0     5.0     5.0     2.0     1.0     5.0      5.0
7433     3.0     2.0     3.0     3.0     2.0     2.0     2.0     3.0      3.0
7434     3.0     1.0     1.0     3.0     5.0     1.0     1.0     1.0      5.0

     RW6_1_11
7430      3.0
7431      3.0
7432      4.0
7433      3.0
7434      1.0
7430             [1, 1, 1, 1, 6]
7431             [1, 1, 2, 4, 2]
7432    [1, 1, 1, 2, 1, 1, 2, 1]
7433             [1, 1, 2, 3, 3]
7434       [1, 2, 1, 1, 3, 1, 1]
dtype: object
      maxLongString_trustPolit  meanLongString_trustPolit  \
7430                       6.0                   2.000000
7431                       4.0                   2.000000
7432                       2.0                   1.250000
7433                       3.0                   2.000000
7434                       3.0                   1.428571

      countLongString_trustPolit
7430                         1.0
7431                         0.0
7432                         0.0
7433                         0.0
7434                         0.0

In [97]:
name = 'CovidImpact_inHouse'
input_vars = data.loc[:, "RW21_1_1":"RW21_1_6"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW21_1_1 RW21_1_2 RW21_1_3 RW21_1_4 RW21_1_5 RW21_1_6
7430        0        0        0      NaN        0      1.0
7431      1.0        0        0      NaN        0        0
7432      1.0        0        0      NaN        0        0
7433        0        0        0      NaN        0      1.0
7434        0        0        0      NaN        0      1.0
7430    [3, 1]
7431    [1, 3]
7432    [1, 3]
7433    [3, 1]
7434    [3, 1]
dtype: object
      maxLongString_CovidImpact_inHouse  meanLongString_CovidImpact_inHouse  \
7430                                  3                                 2.0
7431                                  3                                 2.0
7432                                  3                                 2.0
7433                                  3                                 2.0
7434                                  3                                 2.0

      countLongString_CovidImpact_inHouse
7430                                    0
7431                                    0
7432                                    0
7433                                    0
7434                                    0

In [98]:
data.loc[1797:1807, 'wave']

1797    2
1798    2
1799    2
1800    2
1801    2
1802    2
1803    2
1804    2
1805    2
1806    2
1807    2
Name: wave, dtype: object

In [99]:
data.loc[1797:1807, "RW21_1_1":"RW21_1_6"]

     RW21_1_1 RW21_1_2 RW21_1_3 RW21_1_4 RW21_1_5 RW21_1_6
1797      1.0        0        0        0        0      NaN
1798      1.0        0        0        0        0      NaN
1799      1.0        0        0        0        0      NaN
1800        0        0        0        0        0      NaN
1801        0        0        0        0      1.0      NaN
1802        0        0        0        0      1.0      NaN
1803        0        0        0        0        0      NaN
1804        0        0        0        0        0      NaN
1805        0        0        0        0        0      NaN
1806        0        0        0        0        0      NaN
1807        0        0      1.0        0        0      NaN

In [100]:
name = 'CovidImpact_hasCvd'
input_vars = data.loc[:, "RW21_2_1":"RW21_2_6"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW21_2_1 RW21_2_2 RW21_2_3 RW21_2_4 RW21_2_5 RW21_2_6
7430        0        0        0        0        0      1.0
7431        0        0        0        0        0      1.0
7432        0        0        0        0        0      1.0
7433      1.0        0        0        0        0        0
7434        0        0        0        0        0      1.0
7430    [5, 1]
7431    [5, 1]
7432    [5, 1]
7433    [1, 5]
7434    [5, 1]
dtype: object
      maxLongString_CovidImpact_hasCvd  meanLongString_CovidImpact_hasCvd  \
7430                                 5                                3.0
7431                                 5                                3.0
7432                                 5                                3.0
7433                                 5                                3.0
7434                                 5                                3.0

      countLongString_CovidImpact_hasCvd
7430                                   1
7431                                   1
7432                                   1
7433                                   1
7434                                   1

In [101]:
name = 'CovidImpact_posTest'
input_vars = data.loc[:, "RW21_3_1":"RW21_3_6"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW21_3_1 RW21_3_2 RW21_3_3 RW21_3_4 RW21_3_5 RW21_3_6
7430        0        0        0        0        0      1.0
7431        0        0        0        0        0      1.0
7432        0        0        0        0        0      1.0
7433        0        0        0        0        0      1.0
7434        0        0        0        0        0      1.0
7430    [5, 1]
7431    [5, 1]
7432    [5, 1]
7433    [5, 1]
7434    [5, 1]
dtype: object
      maxLongString_CovidImpact_posTest  meanLongString_CovidImpact_posTest  \
7430                                  5                                 3.0
7431                                  5                                 3.0
7432                                  5                                 3.0
7433                                  5                                 3.0
7434                                  5                                 3.0

      countLongString_CovidImpact_posTest
7430                                    1
7431                                    1
7432                                    1
7433                                    1
7434                                    1

In [102]:
name = 'CovidImpact_hospital'
input_vars = data.loc[:, "RW21_4_1":"RW21_4_6"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW21_4_1 RW21_4_2 RW21_4_3 RW21_4_4 RW21_4_5 RW21_4_6
7430        0        0        0        0        0      1.0
7431        0        0        0        0        0      1.0
7432        0        0        0        0        0      1.0
7433        0        0        0        0        0      1.0
7434        0        0        0        0        0      1.0
7430    [5, 1]
7431    [5, 1]
7432    [5, 1]
7433    [5, 1]
7434    [5, 1]
dtype: object
      maxLongString_CovidImpact_hospital  meanLongString_CovidImpact_hospital  \
7430                                   5                                  3.0
7431                                   5                                  3.0
7432                                   5                                  3.0
7433                                   5                                  3.0
7434                                   5                                  3.0

      countLongString_CovidImpact_hospital
7430                                     1
7431                                     1
7432                                     1
7433                                     1
7434                                     1

In [103]:
name = 'CovidImpact_deceased'
input_vars = data.loc[:, "RW21_5_1":"RW21_5_6"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW21_5_1 RW21_5_2 RW21_5_3 RW21_5_4 RW21_5_5 RW21_5_6
7430        0        0        0        0        0      1.0
7431      1.0        0        0        0        0        0
7432      1.0        0        0        0        0        0
7433        0        0        0        0        0      1.0
7434        0        0        0        0        0      1.0
7430    [5, 1]
7431    [1, 5]
7432    [1, 5]
7433    [5, 1]
7434    [5, 1]
dtype: object
      maxLongString_CovidImpact_deceased  meanLongString_CovidImpact_deceased  \
7430                                   5                                  3.0
7431                                   5                                  3.0
7432                                   5                                  3.0
7433                                   5                                  3.0
7434                                   5                                  3.0

      countLongString_CovidImpact_deceased
7430                                     1
7431                                     1
7432                                     1
7433                                     1
7434                                     1

In [104]:
name = 'CovidImpact_NA'
input_vars = data.loc[:, "RW21_6_1":"RW21_6_6"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW21_6_1 RW21_6_2 RW21_6_3 RW21_6_4 RW21_6_5 RW21_6_6
7430        0        0        0        0        0      1.0
7431        0        0        0        0        0      1.0
7432        0        0        0        0        0      1.0
7433        0        0        0        0        0      1.0
7434        0        0        0        0        0      1.0
7430    [5, 1]
7431    [5, 1]
7432    [5, 1]
7433    [5, 1]
7434    [5, 1]
dtype: object
      maxLongString_CovidImpact_NA  meanLongString_CovidImpact_NA  \
7430                             5                            3.0
7431                             5                            3.0
7432                             5                            3.0
7433                             5                            3.0
7434                             5                            3.0

      countLongString_CovidImpact_NA
7430                               1
7431                               1
7432                               1
7433                               1
7434                               1

In [105]:
name = 'approve'
input_vars = data.loc[:, "RW25_1":"RW25_8"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW25_1 RW25_2 RW25_3 RW25_4 RW25_5 RW25_6 RW25_7 RW25_8
7430    2.0    3.0    3.0    1.0    5.0    3.0    3.0    3.0
7431    5.0    4.0    5.0    5.0    5.0    4.0    4.0    2.0
7432    4.0    4.0    4.0    4.0    7.0    2.0    2.0    3.0
7433    4.0    3.0    3.0    4.0    3.0    3.0    3.0    3.0
7434    5.0    2.0    4.0    5.0    5.0    2.0    2.0    1.0
7430       [1, 2, 1, 1, 3]
7431       [1, 1, 3, 2, 1]
7432          [4, 1, 2, 1]
7433          [1, 2, 1, 4]
7434    [1, 1, 1, 2, 2, 1]
dtype: object
      maxLongString_approve  meanLongString_approve  countLongString_approve
7430                      3                1.600000                        0
7431                      3                1.600000                        0
7432                      4                2.000000                        0
7433                      4                2.000000                        0
7434                      2                1.333333                        0

In [106]:
name = 'CvdPrevent'
input_vars = data.loc[:, "RW26_1":"RW26_18"].columns
validation, data = run_analysis(data, validation, name, input_vars, '6')

     RW26_1 RW26_2 RW26_3 RW26_4 RW26_5 RW26_6 RW26_7 RW26_8 RW26_9 RW26_10  \
7430    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0     1.0
7431    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0     1.0
7432    2.0    1.0    2.0    1.0    1.0    1.0    1.0    2.0    1.0     1.0
7433    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0     1.0
7434    1.0    1.0    1.0    1.0    1.0    1.0    1.0    3.0    3.0     1.0

     RW26_11 RW26_12 RW26_13 RW26_14 RW26_15 RW26_16 RW26_17 RW26_18
7430     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0
7431     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0
7432     1.0     1.0     1.0     1.0     1.0     1.0     2.0     3.0
7433     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0
7434     1.0     2.0     3.0     1.0     1.0     1.0     3.0     3.0
7430                        [18]
7431                        [18]
7432    [1, 1, 1, 4, 1, 8, 1, 1]
7433                        [18]
7434       [7, 2, 2, 1, 1, 3, 2]
dtype: object
      maxLongString_CvdPrevent  meanLongString_CvdPrevent  \
7430                        18                  18.000000
7431                        18                  18.000000
7432                         8                   2.250000
7433                        18                  18.000000
7434                         7                   2.571429

      countLongString_CvdPrevent
7430                           1
7431                           1
7432                           1
7433                           1
7434                           1

In [107]:
name = 'protest2'
input_vars = construct_vars('GFPS2_', 11, skip=[6])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS2_1 GFPS2_2 GFPS2_3 GFPS2_4 GFPS2_5 GFPS2_7 GFPS2_8 GFPS2_9 GFPS2_10  \
8608     1.0     2.0     2.0     3.0     2.0     3.0     2.0     2.0      1.0
8609     2.0     2.0     2.0     2.0     2.0     2.0     2.0     2.0      2.0
8610     1.0     2.0     2.0     3.0     2.0     1.0     2.0     1.0      1.0
8611     1.0     2.0     2.0     1.0     2.0     1.0     2.0     2.0      1.0
8612     1.0     2.0     2.0     3.0     2.0     3.0     2.0     2.0      2.0

     GFPS2_11
8608      1.0
8609      1.0
8610      1.0
8611      1.0
8612      1.0
8608    [1, 2, 1, 1, 1, 2, 2]
8609                   [9, 1]
8610    [1, 2, 1, 1, 1, 1, 3]
8611    [1, 2, 1, 1, 1, 2, 2]
8612    [1, 2, 1, 1, 1, 3, 1]
dtype: object
      maxLongString_protest2  meanLongString_protest2  \
8608                     2.0                 1.428571
8609                     9.0                 5.000000
8610                     3.0                 1.428571
8611                     2.0                 1.428571
8612                     3.0                 1.428571

      countLongString_protest2
8608                       0.0
8609                       1.0
8610                       0.0
8611                       0.0
8612                       0.0

In [108]:
name = 'protest4'
input_vars = construct_vars('GFPS4_', 7, skip=[3,5])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS4_1 GFPS4_2 GFPS4_4 GFPS4_6 GFPS4_7
8608       0       0       0       0       0
8609       0       0       0       0       0
8610       0       0       0       0       0
8611       0       0       0       0       0
8612       0       0       0       0       0
8608    [5]
8609    [5]
8610    [5]
8611    [5]
8612    [5]
dtype: object
      maxLongString_protest4  meanLongString_protest4  \
8608                     5.0                      5.0
8609                     5.0                      5.0
8610                     5.0                      5.0
8611                     5.0                      5.0
8612                     5.0                      5.0

      countLongString_protest4
8608                       1.0
8609                       1.0
8610                       1.0
8611                       1.0
8612                       1.0

In [109]:
name = 'protest5'
input_vars = construct_vars('GFPS5_', 7, skip=[6])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS5_1 GFPS5_2 GFPS5_3 GFPS5_4 GFPS5_5 GFPS5_7
8608       0       0       0       0       0       0
8609       0       0       0       0       0       0
8610       0       0       0       0       0       0
8611       0       0       0       0       0       0
8612       0       0       0       0       0       0
8608    [6]
8609    [6]
8610    [6]
8611    [6]
8612    [6]
dtype: object
      maxLongString_protest5  meanLongString_protest5  \
8608                     6.0                      6.0
8609                     6.0                      6.0
8610                     6.0                      6.0
8611                     6.0                      6.0
8612                     6.0                      6.0

      countLongString_protest5
8608                       1.0
8609                       1.0
8610                       1.0
8611                       1.0
8612                       1.0

In [110]:
name = 'protest6_happened'
input_vars = construct_vars('GFPS6_', 12, '_1', skip=[1,2,3,5,6,8])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS6_4_1 GFPS6_7_1 GFPS6_9_1 GFPS6_10_1 GFPS6_11_1 GFPS6_12_1
8608       NaN         0         0          0          0          0
8609       NaN         0         0          0          0          0
8610       NaN         0         0          0          0          0
8611       NaN         0         0          0          0          0
8612       NaN         0         0          0          0          0
8608    [5]
8609    [5]
8610    [5]
8611    [5]
8612    [5]
dtype: object
      maxLongString_protest6_happened  meanLongString_protest6_happened  \
8608                              5.0                               5.0
8609                              5.0                               5.0
8610                              5.0                               5.0
8611                              5.0                               5.0
8612                              5.0                               5.0

      countLongString_protest6_happened
8608                                1.0
8609                                1.0
8610                                1.0
8611                                1.0
8612                                1.0

In [111]:
name = 'protest6_witnessed'
input_vars = construct_vars('GFPS6_', 12, '_3', skip=[1,2,3,5,6,8])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS6_4_3 GFPS6_7_3 GFPS6_9_3 GFPS6_10_3 GFPS6_11_3 GFPS6_12_3
8608         0         0         0          0          0          0
8609         0         0         0          0          0          0
8610         0         0         0          0          0          0
8611         0         0         0          0          0          0
8612         0         0         0          0          0          0
8608    [6]
8609    [6]
8610    [6]
8611    [6]
8612    [6]
dtype: object
      maxLongString_protest6_witnessed  meanLongString_protest6_witnessed  \
8608                               6.0                                6.0
8609                               6.0                                6.0
8610                               6.0                                6.0
8611                               6.0                                6.0
8612                               6.0                                6.0

      countLongString_protest6_witnessed
8608                                 1.0
8609                                 1.0
8610                                 1.0
8611                                 1.0
8612                                 1.0

In [112]:
name = 'protest6_learned'
input_vars = construct_vars('GFPS6_', 12, '_4', skip=[1,2,3,5,6,8])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS6_4_4 GFPS6_7_4 GFPS6_9_4 GFPS6_10_4 GFPS6_11_4 GFPS6_12_4
8608         0         0         0          0          0          0
8609         0         0         0          0          0          0
8610         0         0         0          0          0          0
8611         0         0         0          0          0          0
8612         0         0         0          0          0          0
8608    [6]
8609    [6]
8610    [6]
8611    [6]
8612    [6]
dtype: object
      maxLongString_protest6_learned  meanLongString_protest6_learned  \
8608                             6.0                              6.0
8609                             6.0                              6.0
8610                             6.0                              6.0
8611                             6.0                              6.0
8612                             6.0                              6.0

      countLongString_protest6_learned
8608                               1.0
8609                               1.0
8610                               1.0
8611                               1.0
8612                               1.0

In [113]:
name = 'protest6_no'
input_vars = construct_vars('GFPS6_', 12, '_5', skip=[1,2,3,5,6,8])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS6_4_5 GFPS6_7_5 GFPS6_9_5 GFPS6_10_5 GFPS6_11_5 GFPS6_12_5
8608         0         0         0          0          0          0
8609         0         0         0          0          0          0
8610         0         0         0          0          0          0
8611         0         0         0          0          0          0
8612         0         0         0          0          0          0
8608    [6]
8609    [6]
8610    [6]
8611    [6]
8612    [6]
dtype: object
      maxLongString_protest6_no  meanLongString_protest6_no  \
8608                        6.0                         6.0
8609                        6.0                         6.0
8610                        6.0                         6.0
8611                        6.0                         6.0
8612                        6.0                         6.0

      countLongString_protest6_no
8608                          1.0
8609                          1.0
8610                          1.0
8611                          1.0
8612                          1.0

In [114]:
name = 'protest6_noDisclose'
input_vars = construct_vars('GFPS6_', 12, '_6', skip=[1,2,3,5,6,8])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS6_4_6 GFPS6_7_6 GFPS6_9_6 GFPS6_10_6 GFPS6_11_6 GFPS6_12_6
8608         0         0         0          0          0          0
8609         0         0         0          0          0          0
8610         0         0         0          0          0          0
8611         0         0         0          0          0          0
8612         0         0         0          0          0          0
8608    [6]
8609    [6]
8610    [6]
8611    [6]
8612    [6]
dtype: object
      maxLongString_protest6_noDisclose  meanLongString_protest6_noDisclose  \
8608                                6.0                                 6.0
8609                                6.0                                 6.0
8610                                6.0                                 6.0
8611                                6.0                                 6.0
8612                                6.0                                 6.0

      countLongString_protest6_noDisclose
8608                                  1.0
8609                                  1.0
8610                                  1.0
8611                                  1.0
8612                                  1.0

In [115]:
name = 'protest6_NA'
input_vars = construct_vars('GFPS6_', 12, '_7', skip=[1,2,3,5,6,8])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS6_4_7 GFPS6_7_7 GFPS6_9_7 GFPS6_10_7 GFPS6_11_7 GFPS6_12_7
8608       1.0       1.0       1.0        1.0        1.0        1.0
8609       1.0       1.0       1.0        1.0        1.0        1.0
8610       1.0       1.0       1.0        1.0        1.0        1.0
8611       1.0       1.0       1.0        1.0        1.0        1.0
8612       1.0       1.0       1.0        1.0        1.0        1.0
8608    [6]
8609    [6]
8610    [6]
8611    [6]
8612    [6]
dtype: object
      maxLongString_protest6_NA  meanLongString_protest6_NA  \
8608                        6.0                         6.0
8609                        6.0                         6.0
8610                        6.0                         6.0
8611                        6.0                         6.0
8612                        6.0                         6.0

      countLongString_protest6_NA
8608                          1.0
8609                          1.0
8610                          1.0
8611                          1.0
8612                          1.0

In [116]:
name = 'protest9'
input_vars = construct_vars('GFPS9_', 7)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS9_1 GFPS9_2 GFPS9_3 GFPS9_4 GFPS9_5 GFPS9_6 GFPS9_7
8608     6.0     1.0     5.0     7.0     6.0     3.0     4.0
8609     6.0     1.0     1.0     6.0     6.0     1.0     1.0
8610     5.0     1.0     2.0     6.0     5.0     6.0     5.0
8611     5.0     1.0     5.0     7.0     7.0     4.0     4.0
8612     6.0     1.0     4.0     7.0     6.0     5.0     1.0
8608    [1, 1, 1, 1, 1, 1, 1]
8609             [1, 2, 2, 2]
8610    [1, 1, 1, 1, 1, 1, 1]
8611          [1, 1, 1, 2, 2]
8612    [1, 1, 1, 1, 1, 1, 1]
dtype: object
      maxLongString_protest9  meanLongString_protest9  \
8608                     1.0                     1.00
8609                     2.0                     1.75
8610                     1.0                     1.00
8611                     2.0                     1.40
8612                     1.0                     1.00

      countLongString_protest9
8608                       0.0
8609                       0.0
8610                       0.0
8611                       0.0
8612                       0.0

In [117]:
name = 'protest10'
input_vars = construct_vars('GFPS10_', 8)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS10_1 GFPS10_2 GFPS10_3 GFPS10_4 GFPS10_5 GFPS10_6 GFPS10_7 GFPS10_8
8608      1.0      6.0      3.0      4.0      5.0      1.0      5.0      4.0
8609      2.0      2.0      1.0      3.0      4.0      1.0      2.0      5.0
8610      1.0      6.0      2.0      1.0      6.0      1.0      5.0      6.0
8611      1.0      6.0      6.0      1.0      6.0      1.0      4.0      6.0
8612      3.0      4.0      7.0      2.0      5.0      2.0      1.0      4.0
8608    [1, 1, 1, 1, 1, 1, 1, 1]
8609       [2, 1, 1, 1, 1, 1, 1]
8610    [1, 1, 1, 1, 1, 1, 1, 1]
8611       [1, 2, 1, 1, 1, 1, 1]
8612    [1, 1, 1, 1, 1, 1, 1, 1]
dtype: object
      maxLongString_protest10  meanLongString_protest10  \
8608                      1.0                  1.000000
8609                      2.0                  1.142857
8610                      1.0                  1.000000
8611                      2.0                  1.142857
8612                      1.0                  1.000000

      countLongString_protest10
8608                        0.0
8609                        0.0
8610                        0.0
8611                        0.0
8612                        0.0

In [118]:
name = 'protest11'
input_vars = construct_vars('GFPS11_', 7)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS11_1 GFPS11_2 GFPS11_3 GFPS11_4 GFPS11_5 GFPS11_6 GFPS11_7
8608      4.0      1.0      1.0      1.0      1.0      2.0      2.0
8609      1.0      4.0      1.0      1.0      1.0      1.0      1.0
8610      2.0      2.0      4.0      3.0      2.0      6.0      5.0
8611      1.0      6.0      1.0      1.0      1.0      1.0      1.0
8612      5.0      4.0      2.0      4.0      2.0      3.0      2.0
8608                [1, 4, 2]
8609                [1, 1, 5]
8610       [2, 1, 1, 1, 1, 1]
8611                [1, 1, 5]
8612    [1, 1, 1, 1, 1, 1, 1]
dtype: object
      maxLongString_protest11  meanLongString_protest11  \
8608                      4.0                  2.333333
8609                      5.0                  2.333333
8610                      2.0                  1.166667
8611                      5.0                  2.333333
8612                      1.0                  1.000000

      countLongString_protest11
8608                        0.0
8609                        1.0
8610                        0.0
8611                        1.0
8612                        0.0

In [119]:
name = 'protest12'
input_vars = construct_vars('GFPS12_', 8)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS12_1 GFPS12_2 GFPS12_3 GFPS12_4 GFPS12_5 GFPS12_6 GFPS12_7 GFPS12_8
8608      3.0      4.0      7.0      4.0      2.0      4.0      1.0      3.0
8609      4.0      1.0      1.0      1.0      3.0      4.0      1.0      3.0
8610      3.0      5.0      5.0      3.0      5.0      3.0      3.0      5.0
8611      6.0      4.0      7.0      7.0      5.0      7.0      1.0      5.0
8612      4.0      1.0      7.0      5.0      2.0      4.0      1.0      1.0
8608    [1, 1, 1, 1, 1, 1, 1, 1]
8609          [1, 3, 1, 1, 1, 1]
8610          [1, 2, 1, 1, 2, 1]
8611       [1, 1, 2, 1, 1, 1, 1]
8612       [1, 1, 1, 1, 1, 1, 2]
dtype: object
      maxLongString_protest12  meanLongString_protest12  \
8608                      1.0                  1.000000
8609                      3.0                  1.333333
8610                      2.0                  1.333333
8611                      2.0                  1.142857
8612                      2.0                  1.142857

      countLongString_protest12
8608                        0.0
8609                        0.0
8610                        0.0
8611                        0.0
8612                        0.0

In [120]:
name = 'protest13'
input_vars = construct_vars('GFPS13_', 7)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS13_1 GFPS13_2 GFPS13_3 GFPS13_4 GFPS13_5 GFPS13_6 GFPS13_7
8608      6.0      1.0      1.0      6.0      6.0      4.0      5.0
8609      6.0      1.0      3.0      2.0      4.0      2.0      1.0
8610      4.0      1.0      4.0      3.0      2.0      6.0      6.0
8611      5.0      1.0      4.0      6.0      6.0      6.0      6.0
8612      4.0      1.0      2.0      7.0      7.0      6.0      3.0
8608          [1, 2, 2, 1, 1]
8609    [1, 1, 1, 1, 1, 1, 1]
8610       [1, 1, 1, 1, 1, 2]
8611             [1, 1, 1, 4]
8612       [1, 1, 1, 2, 1, 1]
dtype: object
      maxLongString_protest13  meanLongString_protest13  \
8608                      2.0                  1.400000
8609                      1.0                  1.000000
8610                      2.0                  1.166667
8611                      4.0                  1.750000
8612                      2.0                  1.166667

      countLongString_protest13
8608                        0.0
8609                        0.0
8610                        0.0
8611                        0.0
8612                        0.0

In [121]:
name = 'protest14'
input_vars = construct_vars('GFPS14_', 8)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS14_1 GFPS14_2 GFPS14_3 GFPS14_4 GFPS14_5 GFPS14_6 GFPS14_7 GFPS14_8
8608      1.0      6.0      4.0      2.0      6.0      1.0      5.0      5.0
8609      3.0      3.0      1.0      2.0      2.0      1.0      1.0      5.0
8610      2.0      5.0      3.0      2.0      6.0      4.0      5.0      6.0
8611      2.0      5.0      6.0      2.0      5.0      2.0      3.0      4.0
8612      2.0      6.0      6.0      2.0      7.0      1.0      4.0      5.0
8608       [1, 1, 1, 1, 1, 1, 2]
8609             [2, 1, 2, 2, 1]
8610    [1, 1, 1, 1, 1, 1, 1, 1]
8611    [1, 1, 1, 1, 1, 1, 1, 1]
8612       [1, 2, 1, 1, 1, 1, 1]
dtype: object
      maxLongString_protest14  meanLongString_protest14  \
8608                      2.0                  1.142857
8609                      2.0                  1.600000
8610                      1.0                  1.000000
8611                      1.0                  1.000000
8612                      2.0                  1.142857

      countLongString_protest14
8608                        0.0
8609                        0.0
8610                        0.0
8611                        0.0
8612                        0.0

In [122]:
name = 'protest15'
input_vars = construct_vars('GFPS15_', 7)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS15_1 GFPS15_2 GFPS15_3 GFPS15_4 GFPS15_5 GFPS15_6 GFPS15_7
8608      6.0      1.0      1.0      6.0      6.0      5.0      5.0
8609      6.0      1.0      1.0      4.0      6.0      2.0      2.0
8610      4.0      1.0      5.0      6.0      5.0      7.0      7.0
8611      5.0      1.0      4.0      4.0      5.0      4.0      4.0
8612      6.0      1.0      2.0      7.0      7.0      6.0      5.0
8608          [1, 2, 2, 2]
8609       [1, 2, 1, 1, 2]
8610    [1, 1, 1, 1, 1, 2]
8611       [1, 1, 2, 1, 2]
8612    [1, 1, 1, 2, 1, 1]
dtype: object
      maxLongString_protest15  meanLongString_protest15  \
8608                      2.0                  1.750000
8609                      2.0                  1.400000
8610                      2.0                  1.166667
8611                      2.0                  1.400000
8612                      2.0                  1.166667

      countLongString_protest15
8608                        0.0
8609                        0.0
8610                        0.0
8611                        0.0
8612                        0.0

In [123]:
name = 'protest16'
input_vars = construct_vars('GFPS16_', 8)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS16_1 GFPS16_2 GFPS16_3 GFPS16_4 GFPS16_5 GFPS16_6 GFPS16_7 GFPS16_8
8608      1.0      6.0      4.0      2.0      6.0      1.0      4.0      6.0
8609      2.0      2.0      1.0      2.0      3.0      2.0      1.0      1.0
8610      1.0      6.0      2.0      1.0      7.0      2.0      6.0      7.0
8611      2.0      5.0      5.0      2.0      5.0      2.0      3.0      4.0
8612      1.0      6.0      5.0      4.0      6.0      1.0      3.0      5.0
8608    [1, 1, 1, 1, 1, 1, 1, 1]
8609          [2, 1, 1, 1, 1, 2]
8610    [1, 1, 1, 1, 1, 1, 1, 1]
8611       [1, 2, 1, 1, 1, 1, 1]
8612    [1, 1, 1, 1, 1, 1, 1, 1]
dtype: object
      maxLongString_protest16  meanLongString_protest16  \
8608                      1.0                  1.000000
8609                      2.0                  1.333333
8610                      1.0                  1.000000
8611                      2.0                  1.142857
8612                      1.0                  1.000000

      countLongString_protest16
8608                        0.0
8609                        0.0
8610                        0.0
8611                        0.0
8612                        0.0

In [124]:
name = 'protest17'
input_vars = construct_vars('GFPS17_', 12, skip=[4,5,7])
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS17_1 GFPS17_2 GFPS17_3 GFPS17_6 GFPS17_8 GFPS17_9 GFPS17_10  \
8608      5.0      1.0      1.0      1.0      1.0      7.0       1.0
8609      2.0      5.0      5.0      6.0      5.0      5.0       1.0
8610      6.0      6.0      6.0      1.0      6.0      6.0       1.0
8611      2.0      5.0      5.0      7.0      5.0      5.0       1.0
8612      5.0      5.0      6.0      5.0      6.0      6.0       5.0

     GFPS17_11 GFPS17_12
8608       1.0       1.0
8609       3.0       1.0
8610       6.0       7.0
8611       2.0       4.0
8612       5.0       6.0
8608             [1, 4, 1, 3]
8609    [1, 2, 1, 2, 1, 1, 1]
8610       [3, 1, 2, 1, 1, 1]
8611    [1, 2, 1, 2, 1, 1, 1]
8612       [2, 1, 1, 2, 2, 1]
dtype: object
      maxLongString_protest17  meanLongString_protest17  \
8608                      4.0                  2.250000
8609                      2.0                  1.285714
8610                      3.0                  1.500000
8611                      2.0                  1.285714
8612                      2.0                  1.500000

      countLongString_protest17
8608                        0.0
8609                        0.0
8610                        0.0
8611                        0.0
8612                        0.0

In [125]:
name = 'protest33'
input_vars = construct_vars('GFPS33_', 5)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     GFPS33_1 GFPS33_2 GFPS33_3 GFPS33_4 GFPS33_5
8608      2.0      2.0      2.0      2.0      2.0
8609      2.0      2.0      2.0      2.0      2.0
8610      2.0      2.0      2.0      2.0      2.0
8611      2.0      2.0      2.0      2.0      2.0
8612      2.0      2.0      2.0      2.0      2.0
8608    [5]
8609    [5]
8610    [5]
8611    [5]
8612    [5]
dtype: object
      maxLongString_protest33  meanLongString_protest33  \
8608                      5.0                       5.0
8609                      5.0                       5.0
8610                      5.0                       5.0
8611                      5.0                       5.0
8612                      5.0                       5.0

      countLongString_protest33
8608                        1.0
8609                        1.0
8610                        1.0
8611                        1.0
8612                        1.0

In [126]:
name = 'EES'
input_vars = construct_vars('EES1_', 32)
validation, data = run_analysis(data, validation, name, input_vars, '4')

     EES1_1 EES1_2 EES1_3 EES1_4 EES1_5 EES1_6 EES1_7 EES1_8 EES1_9 EES1_10  \
4757    1.0    2.0    1.0    5.0    1.0    5.0    4.0    1.0    4.0     1.0
4758    5.0    2.0    5.0    1.0    2.0    4.0    6.0    6.0    4.0     3.0
4759    1.0    6.0    6.0    6.0    1.0    6.0    6.0    1.0    6.0     1.0
4760    6.0    4.0    3.0    1.0    3.0    4.0    4.0    3.0    3.0     6.0
4761    2.0    2.0    5.0    6.0    1.0    6.0    6.0    1.0    5.0     1.0

      ... EES1_23 EES1_24 EES1_25 EES1_26 EES1_27 EES1_28 EES1_29 EES1_30  \
4757  ...     5.0     6.0     6.0     5.0     1.0     1.0     1.0     4.0
4758  ...     4.0     6.0     6.0     4.0     1.0     2.0     3.0     3.0
4759  ...     6.0     6.0     6.0     6.0     1.0     1.0     1.0     6.0
4760  ...     4.0     4.0     4.0     4.0     3.0     5.0     3.0     3.0
4761  ...     4.0     4.0     4.0     5.0     2.0     2.0     2.0     2.0

     EES1_31 EES1_32
4757     2.0     5.0
4758     2.0     5.0
4759     1.0     5.0
4760     5.0     5.0
4761     2.0     5.0

[5 rows x 32 columns]
4757    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, ...
4758    [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 1, 1, 1, ...
4759     [1, 3, 1, 2, 1, 1, 1, 5, 2, 3, 1, 5, 3, 1, 1, 1]
4760    [1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, ...
4761    [2, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, ...
dtype: object
      maxLongString_EES  meanLongString_EES  countLongString_EES
4757                3.0            1.185185                  0.0
4758                3.0            1.185185                  0.0
4759                5.0            2.000000                  2.0
4760                5.0            1.523810                  1.0
4761                5.0            1.600000                  1.0

In [127]:
name = 'Dscr'
input_vars = construct_vars('Dscr1_', 9)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     Dscr1_1 Dscr1_2 Dscr1_3 Dscr1_4 Dscr1_5 Dscr1_6 Dscr1_7 Dscr1_8 Dscr1_9
8608     5.0     5.0     5.0     5.0     5.0     5.0     5.0     6.0     6.0
8609     6.0     6.0     6.0     6.0     6.0     6.0     6.0     6.0     6.0
8610     5.0     5.0     5.0     5.0     6.0     5.0     5.0     6.0     5.0
8611     5.0     5.0     5.0     5.0     5.0     5.0     5.0     5.0     5.0
8612     4.0     4.0     4.0     6.0     6.0     5.0     5.0     6.0     6.0
8608             [7, 2]
8609                [9]
8610    [4, 1, 2, 1, 1]
8611                [9]
8612       [3, 2, 2, 2]
dtype: object
      maxLongString_Dscr  meanLongString_Dscr  countLongString_Dscr
8608                 7.0                 4.50                   1.0
8609                 9.0                 9.00                   1.0
8610                 4.0                 1.80                   0.0
8611                 9.0                 9.00                   1.0
8612                 3.0                 2.25                   0.0

In [128]:
name = 'FWI'
input_vars = construct_vars('FWI1_', 15)
validation, data = run_analysis(data, validation, name, input_vars, '3')

     FWI1_1 FWI1_2 FWI1_3 FWI1_4 FWI1_5 FWI1_6 FWI1_7 FWI1_8 FWI1_9 FWI1_10  \
3295    5.0    5.0    5.0    6.0    5.0    6.0    5.0    5.0    5.0     6.0
3296    5.0    4.0    5.0    5.0    4.0    5.0    5.0    4.0    5.0     5.0
3297    4.0    3.0    3.0    3.0    2.0    1.0    3.0    2.0    3.0     3.0
3298    3.0    2.0    2.0    3.0    6.0    2.0    4.0    2.0    2.0     4.0
3299    7.0    5.0    5.0    6.0    6.0    5.0    5.0    5.0    4.0     4.0

     FWI1_11 FWI1_12 FWI1_13 FWI1_14 FWI1_15
3295     5.0     5.0     6.0     5.0     6.0
3296     4.0     5.0     5.0     4.0     6.0
3297     1.0     4.0     4.0     3.0     5.0
3298     2.0     6.0     6.0     4.0     4.0
3299     2.0     7.0     4.0     2.0     2.0
3295       [3, 1, 1, 1, 3, 1, 2, 1, 1, 1]
3296    [1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1]
3297    [1, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1]
3298    [1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2]
3299          [1, 2, 2, 3, 2, 1, 1, 1, 2]
dtype: object
      maxLongString_FWI  meanLongString_FWI  countLongString_FWI
3295                3.0            1.500000                  0.0
3296                2.0            1.363636                  0.0
3297                3.0            1.363636                  0.0
3298                2.0            1.363636                  0.0
3299                3.0            1.666667                  0.0

In [129]:
data.loc[9917:9927, 'wave']

9917    8
9918    8
9919    8
9920    8
9921    8
9922    8
9923    8
9924    8
9925    8
9926    8
9927    8
Name: wave, dtype: object

In [130]:
name = 'hum'
input_vars = construct_vars('Hum1_', 10)
validation, data = run_analysis(data, validation, name, input_vars, '7')

     Hum1_1 Hum1_2 Hum1_3 Hum1_4 Hum1_5 Hum1_6 Hum1_7 Hum1_8 Hum1_9 Hum1_10
8608    2.0    2.0    3.0    1.0    5.0    3.0    1.0    3.0    3.0     1.0
8609    6.0    6.0    6.0    6.0    6.0    6.0    6.0    6.0    6.0     6.0
8610    5.0    5.0    5.0    5.0    5.0    5.0    4.0    4.0    3.0     2.0
8611    6.0    6.0    6.0    6.0    6.0    6.0    6.0    6.0    6.0     6.0
8612    5.0    4.0    4.0    4.0    3.0    3.0    3.0    3.0    2.0     2.0
8608    [2, 1, 1, 1, 1, 1, 2, 1]
8609                        [10]
8610                [6, 2, 1, 1]
8611                        [10]
8612                [1, 3, 4, 2]
dtype: object
      maxLongString_hum  meanLongString_hum  countLongString_hum
8608                2.0                1.25                  0.0
8609               10.0               10.00                  1.0
8610                6.0                2.50                  1.0
8611               10.0               10.00                  1.0
8612                4.0                2.50                  0.0

In [131]:
name = 'PC'
input_vars = construct_vars('PC5.2_', 5)
validation, data = run_analysis(data, validation, name, input_vars, '4')

     PC5.2_1 PC5.2_2 PC5.2_3 PC5.2_4 PC5.2_5
4757     2.0     1.0     2.0     2.0     2.0
4758       0       0       0       0       0
4759     2.0     2.0     1.0     2.0     2.0
4760       0       0       0       0       0
4761     2.0     2.0     2.0     2.0     2.0
4757    [1, 1, 3]
4758          [5]
4759    [2, 1, 2]
4760          [5]
4761          [5]
dtype: object
      maxLongString_PC  meanLongString_PC  countLongString_PC
4757               3.0           1.666667                 0.0
4758               5.0           5.000000                 1.0
4759               2.0           1.666667                 0.0
4760               5.0           5.000000                 1.0
4761               5.0           5.000000                 1.0

In [132]:
name = 'PPK'
input_vars = construct_vars('CvPP1_', 12)
validation, data = run_analysis(data, validation, name, input_vars, '6')

     CvPP1_1 CvPP1_2 CvPP1_3 CvPP1_4 CvPP1_5 CvPP1_6 CvPP1_7 CvPP1_8 CvPP1_9  \
7430     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0
7431     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0
7432     1.0     1.0     1.0     1.0     4.0     1.0     2.0     1.0     4.0
7433     2.0     2.0     2.0     2.0     2.0     2.0     2.0     2.0     1.0
7434     1.0     1.0     1.0     1.0     1.0     2.0     2.0     2.0     2.0

     CvPP1_10 CvPP1_11 CvPP1_12
7430      1.0      1.0      1.0
7431      1.0      1.0      1.0
7432      3.0      3.0      3.0
7433      1.0      1.0      1.0
7434      1.0      1.0      1.0
7430                     [12]
7431                     [12]
7432    [4, 1, 1, 1, 1, 1, 3]
7433                   [8, 4]
7434                [5, 4, 3]
dtype: object
      maxLongString_PPK  meanLongString_PPK  countLongString_PPK
7430               12.0           12.000000                  1.0
7431               12.0           12.000000                  1.0
7432                4.0            1.714286                  0.0
7433                8.0            6.000000                  1.0
7434                5.0            4.000000                  1.0

In [133]:
name = 'ResSe'
input_vars = construct_vars('ReSe1_', 22)
validation, data = run_analysis(data, validation, name, input_vars, '6')

     ReSe1_1 ReSe1_2 ReSe1_3 ReSe1_4 ReSe1_5 ReSe1_6 ReSe1_7 ReSe1_8 ReSe1_9  \
7430     3.0     3.0     3.0     4.0     5.0     4.0     3.0     4.0     5.0
7431     4.0     3.0     4.0     3.0     5.0     4.0     5.0     5.0     5.0
7432     4.0     3.0     3.0     3.0     3.0     1.0     5.0     2.0     3.0
7433     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0
7434     2.0     2.0     2.0     2.0     2.0     2.0     4.0     3.0     4.0

     ReSe1_10  ... ReSe1_13 ReSe1_14 ReSe1_15 ReSe1_16 ReSe1_17 ReSe1_18  \
7430      5.0  ...      4.0      4.0      4.0      5.0      5.0      4.0
7431      5.0  ...      5.0      5.0      5.0      5.0      5.0      5.0
7432      2.0  ...      4.0      2.0      4.0      2.0      5.0      2.0
7433      1.0  ...      1.0      1.0      1.0      1.0      1.0      1.0
7434      3.0  ...      4.0      3.0      4.0      3.0      4.0      4.0

     ReSe1_19 ReSe1_20 ReSe1_21 ReSe1_22
7430      4.0      5.0      5.0      5.0
7431      5.0      5.0      5.0      5.0
7432      5.0      2.0      5.0      4.0
7433      1.0      1.0      1.0      1.0
7434      4.0      5.0      5.0      5.0

[5 rows x 22 columns]
7430                    [3, 1, 1, 1, 1, 1, 2, 5, 2, 2, 3]
7431                               [1, 1, 1, 1, 1, 1, 16]
7432    [1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
7433                                                 [22]
7434              [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3]
dtype: object
      maxLongString_ResSe  meanLongString_ResSe  countLongString_ResSe
7430                  5.0              2.000000                    1.0
7431                 16.0              3.142857                    1.0
7432                  4.0              1.157895                    0.0
7433                 22.0             22.000000                    1.0
7434                  6.0              1.692308                    1.0

In [134]:
name = 'SPS_city'
input_vars = construct_vars('City_', 12)
validation, data = run_analysis(data, validation, name, input_vars, '6')

     City_1 City_2 City_3 City_4 City_5 City_6 City_7 City_8 City_9 City_10  \
7430    5.0    3.0    4.0    5.0    5.0    4.0    4.0    5.0    3.0     5.0
7431    7.0    5.0    6.0    5.0    6.0    5.0    5.0    6.0    6.0     5.0
7432    3.0    6.0    2.0    2.0    4.0    5.0    5.0    5.0    5.0     6.0
7433    4.0    4.0    4.0    4.0    5.0    4.0    4.0    5.0    4.0     4.0
7434    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    7.0     7.0

     City_11 City_12
7430     4.0     4.0
7431     5.0     6.0
7432     4.0     3.0
7433     3.0     5.0
7434     1.0     1.0
7430    [1, 1, 1, 2, 2, 1, 1, 1, 2]
7431    [1, 1, 1, 1, 1, 2, 2, 2, 1]
7432       [1, 1, 2, 1, 4, 1, 1, 1]
7433          [4, 1, 2, 1, 2, 1, 1]
7434                      [8, 2, 2]
dtype: object
      maxLongString_SPS_city  meanLongString_SPS_city  \
7430                     2.0                 1.333333
7431                     2.0                 1.333333
7432                     4.0                 1.500000
7433                     4.0                 1.714286
7434                     8.0                 4.000000

      countLongString_SPS_city
7430                       0.0
7431                       0.0
7432                       0.0
7433                       0.0
7434                       1.0

In [135]:
name = 'SPS_state'
input_vars = construct_vars('State_', 12)
validation, data = run_analysis(data, validation, name, input_vars, '6')

     State_1 State_2 State_3 State_4 State_5 State_6 State_7 State_8 State_9  \
7430     4.0     5.0     4.0     5.0     4.0     4.0     5.0     3.0     4.0
7431     6.0     5.0     6.0     6.0     4.0     6.0     6.0     5.0     5.0
7432     6.0     6.0     2.0     2.0     5.0     3.0     5.0     6.0     5.0
7433     4.0     4.0     5.0     4.0     4.0     4.0     4.0     5.0     4.0
7434     7.0     7.0     7.0     7.0     1.0     1.0     7.0     7.0     7.0

     State_10 State_11 State_12
7430      4.0      4.0      4.0
7431      6.0      5.0      5.0
7432      6.0      3.0      3.0
7433      4.0      3.0      4.0
7434      7.0      1.0      1.0
7430       [1, 1, 1, 1, 2, 1, 1, 4]
7431       [1, 1, 2, 1, 2, 2, 1, 2]
7432    [2, 2, 1, 1, 1, 1, 1, 1, 2]
7433          [2, 1, 4, 1, 2, 1, 1]
7434                   [4, 2, 4, 2]
dtype: object
      maxLongString_SPS_state  meanLongString_SPS_state  \
7430                      4.0                  1.500000
7431                      2.0                  1.500000
7432                      2.0                  1.333333
7433                      4.0                  1.714286
7434                      4.0                  3.000000

      countLongString_SPS_state
7430                        0.0
7431                        0.0
7432                        0.0
7433                        0.0
7434                        0.0

In [136]:
name = 'SPS_fed'
input_vars = construct_vars('Fed_', 12)
validation, data = run_analysis(data, validation, name, input_vars, '6')

     Fed_1 Fed_2 Fed_3 Fed_4 Fed_5 Fed_6 Fed_7 Fed_8 Fed_9 Fed_10 Fed_11  \
7430   4.0   4.0   4.0   7.0   5.0   5.0   4.0   6.0   4.0    4.0    2.0
7431   6.0   5.0   5.0   6.0   3.0   6.0   6.0   6.0   4.0    5.0    3.0
7432   4.0   5.0   2.0   4.0   2.0   4.0   5.0   7.0   5.0    5.0    4.0
7433   5.0   4.0   4.0   5.0   4.0   4.0   5.0   4.0   4.0    4.0    5.0
7434   7.0   7.0   1.0   1.0   1.0   1.0   7.0   7.0   7.0    7.0    1.0

     Fed_12
7430    4.0
7431    5.0
7432    4.0
7433    5.0
7434    1.0
7430          [3, 1, 2, 1, 1, 2, 1, 1]
7431       [1, 2, 1, 1, 3, 1, 1, 1, 1]
7432    [1, 1, 1, 1, 1, 1, 1, 1, 2, 2]
7433             [1, 2, 1, 2, 1, 3, 2]
7434                      [2, 4, 4, 2]
dtype: object
      maxLongString_SPS_fed  meanLongString_SPS_fed  countLongString_SPS_fed
7430                    3.0                1.500000                      0.0
7431                    3.0                1.333333                      0.0
7432                    2.0                1.200000                      0.0
7433                    3.0                1.714286                      0.0
7434                    4.0                3.000000                      0.0

In [137]:
name = 'STAI_trait'
input_vars = construct_vars('AnxT_', 20)
validation, data = run_analysis(data, validation, name, input_vars, '1')

  AnxT_1 AnxT_2 AnxT_3 AnxT_4 AnxT_5 AnxT_6 AnxT_7 AnxT_8 AnxT_9 AnxT_10  \
0    3.0    2.0    3.0    4.0    2.0    2.0    3.0    2.0    4.0     3.0
1    2.0    2.0    2.0    4.0    2.0    2.0    2.0    4.0    3.0     2.0
2    4.0    2.0    3.0    2.0    1.0    2.0    4.0    1.0    1.0     4.0
3    1.0    4.0    1.0    2.0    3.0    2.0    2.0    2.0    3.0     2.0
4    3.0    2.0    2.0    4.0    3.0    4.0    4.0    3.0    4.0     3.0

  AnxT_11 AnxT_12 AnxT_13 AnxT_14 AnxT_15 AnxT_16 AnxT_17 AnxT_18 AnxT_19  \
0     2.0     4.0     3.0     3.0     2.0     2.0     3.0     3.0     2.0
1     3.0     1.0     2.0     4.0     2.0     2.0     3.0     3.0     2.0
2     1.0     2.0     4.0     4.0     1.0     2.0     2.0     2.0     3.0
3     2.0     3.0     2.0     1.0     1.0     1.0     3.0     4.0     1.0
4     4.0     4.0     3.0     3.0     3.0     4.0     4.0     3.0     4.0

  AnxT_20
0     1.0
1     3.0
2     1.0
3     1.0
4     4.0
0    [1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1]
1          [3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1]
2    [1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 3, 1, 1]
3          [1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 3, 1, 1, 2]
4             [1, 2, 1, 1, 2, 1, 1, 1, 2, 3, 2, 1, 2]
dtype: object
   maxLongString_STAI_trait  meanLongString_STAI_trait  \
0                       2.0                   1.250000
1                       3.0                   1.428571
2                       3.0                   1.250000
3                       3.0                   1.428571
4                       3.0                   1.538462

   countLongString_STAI_trait
0                         0.0
1                         0.0
2                         0.0
3                         0.0
4                         0.0

In [138]:
name = 'VSA'
input_vars = construct_vars('VSA1_', 6)
validation, data = run_analysis(data, validation, name, input_vars, '1')

  VSA1_1 VSA1_2 VSA1_3 VSA1_4 VSA1_5 VSA1_6
0    1.0    7.0    1.0    7.0    1.0    7.0
1    3.0    2.0    1.0    7.0    6.0    1.0
2    6.0    1.0    1.0    7.0    7.0    2.0
3    1.0    5.0    5.0    7.0    3.0    9.0
4    5.0    6.0    6.0    7.0    6.0    6.0
0    [1, 1, 1, 1, 1, 1]
1    [1, 1, 1, 1, 1, 1]
2          [1, 2, 2, 1]
3       [1, 2, 1, 1, 1]
4          [1, 2, 1, 2]
dtype: object
   maxLongString_VSA  meanLongString_VSA  countLongString_VSA
0                1.0                 1.0                  0.0
1                1.0                 1.0                  0.0
2                2.0                 1.5                  0.0
3                2.0                 1.2                  0.0
4                2.0                 1.5                  0.0

In [139]:
name = 'NEO1'
input_vars = construct_vars('NEO1_', 10)
validation, data = run_analysis(data, validation, name, input_vars, '1')

  NEO1_1 NEO1_2 NEO1_3 NEO1_4 NEO1_5 NEO1_6 NEO1_7 NEO1_8 NEO1_9 NEO1_10
0    2.0    1.0    3.0    5.0    5.0    5.0    2.0    5.0    2.0     5.0
1    2.0    4.0    4.0    5.0    5.0    2.0    3.0    3.0    3.0     5.0
2    4.0    2.0    2.0    4.0    4.0    1.0    5.0    4.0    3.0     4.0
3    1.0    2.0    2.0    3.0    1.0    3.0    1.0    3.0    2.0     2.0
4    2.0    4.0    2.0    2.0    4.0    2.0    4.0    4.0    3.0     4.0
0    [1, 1, 1, 3, 1, 1, 1, 1]
1          [1, 2, 2, 1, 3, 1]
2    [1, 2, 2, 1, 1, 1, 1, 1]
3    [1, 2, 1, 1, 1, 1, 1, 2]
4    [1, 1, 2, 1, 1, 2, 1, 1]
dtype: object
   maxLongString_NEO1  meanLongString_NEO1  countLongString_NEO1
0                 3.0             1.250000                   0.0
1                 3.0             1.666667                   0.0
2                 2.0             1.250000                   0.0
3                 2.0             1.250000                   0.0
4                 2.0             1.250000                   0.0

In [140]:
name = 'NEO2'
input_vars = construct_vars('NEO2_', 10)
validation, data = run_analysis(data, validation, name, input_vars, '1')

  NEO2_1 NEO2_2 NEO2_3 NEO2_4 NEO2_5 NEO2_6 NEO2_7 NEO2_8 NEO2_9 NEO2_10
0    4.0    3.0    5.0    1.0    1.0    1.0    1.0    1.0    4.0     5.0
1    5.0    4.0    5.0    1.0    1.0    1.0    5.0    1.0    5.0     5.0
2    1.0    4.0    4.0    2.0    1.0    2.0    4.0    1.0    2.0     5.0
3    4.0    5.0    5.0    5.0    4.0    1.0    1.0    4.0    1.0     4.0
4    4.0    4.0    4.0    2.0    2.0    2.0    4.0    3.0    3.0     5.0
0             [1, 1, 1, 5, 1, 1]
1          [1, 1, 1, 3, 1, 1, 2]
2    [1, 2, 1, 1, 1, 1, 1, 1, 1]
3          [1, 3, 1, 2, 1, 1, 1]
4                [3, 3, 1, 2, 1]
dtype: object
   maxLongString_NEO2  meanLongString_NEO2  countLongString_NEO2
0                 5.0             1.666667                   1.0
1                 3.0             1.428571                   0.0
2                 2.0             1.111111                   0.0
3                 3.0             1.428571                   0.0
4                 3.0             2.000000                   0.0

In [141]:
name = 'NEO3'
input_vars = construct_vars('NEO3_', 10)
validation, data = run_analysis(data, validation, name, input_vars, '1')

  NEO3_1 NEO3_2 NEO3_3 NEO3_4 NEO3_5 NEO3_6 NEO3_7 NEO3_8 NEO3_9 NEO3_10
0    4.0    1.0    5.0    5.0    5.0    5.0    5.0    2.0    4.0     2.0
1    5.0    3.0    2.0    4.0    5.0    4.0    2.0    5.0    5.0     2.0
2    2.0    2.0    2.0    2.0    3.0    2.0    4.0    2.0    4.0     4.0
3    5.0    3.0    2.0    3.0    4.0    5.0    5.0    3.0    4.0     4.0
4    4.0    4.0    3.0    3.0    3.0    4.0    3.0    4.0    5.0     2.0
0             [1, 1, 5, 1, 1, 1]
1    [1, 1, 1, 1, 1, 1, 1, 2, 1]
2             [4, 1, 1, 1, 1, 2]
3       [1, 1, 1, 1, 1, 2, 1, 2]
4          [2, 3, 1, 1, 1, 1, 1]
dtype: object
   maxLongString_NEO3  meanLongString_NEO3  countLongString_NEO3
0                 5.0             1.666667                   1.0
1                 2.0             1.111111                   0.0
2                 4.0             1.666667                   0.0
3                 2.0             1.250000                   0.0
4                 3.0             1.428571                   0.0

In [142]:
name = 'NEO4'
input_vars = construct_vars('NEO4_', 10)
validation, data = run_analysis(data, validation, name, input_vars, '1')

  NEO4_1 NEO4_2 NEO4_3 NEO4_4 NEO4_5 NEO4_6 NEO4_7 NEO4_8 NEO4_9 NEO4_10
0    1.0    4.0    2.0    5.0    5.0    3.0    2.0    1.0    1.0     5.0
1    1.0    2.0    1.0    3.0    5.0    3.0    2.0    1.0    3.0     4.0
2    4.0    3.0    1.0    3.0    2.0    5.0    4.0    1.0    3.0     5.0
3    1.0    1.0    3.0    1.0    3.0    4.0    1.0    1.0    3.0     1.0
4    4.0    2.0    3.0    4.0    4.0    1.0    4.0    4.0    3.0     3.0
0          [1, 1, 1, 2, 1, 1, 2, 1]
1    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
2    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
3          [2, 1, 1, 1, 1, 2, 1, 1]
4             [1, 1, 1, 2, 1, 2, 2]
dtype: object
   maxLongString_NEO4  meanLongString_NEO4  countLongString_NEO4
0                 2.0             1.250000                   0.0
1                 1.0             1.000000                   0.0
2                 1.0             1.000000                   0.0
3                 2.0             1.250000                   0.0
4                 2.0             1.428571                   0.0

In [143]:
name = 'NEO5'
input_vars = construct_vars('NEO5_', 10)
validation, data = run_analysis(data, validation, name, input_vars, '1')

  NEO5_1 NEO5_2 NEO5_3 NEO5_4 NEO5_5 NEO5_6 NEO5_7 NEO5_8 NEO5_9 NEO5_10
0    4.0    2.0    1.0    1.0    1.0    2.0    3.0    1.0    5.0     5.0
1    4.0    4.0    3.0    3.0    2.0    1.0    2.0    1.0    5.0     4.0
2    3.0    1.0    4.0    3.0    2.0    3.0    1.0    2.0    4.0     4.0
3    5.0    5.0    4.0    2.0    5.0    1.0    1.0    1.0    5.0     3.0
4    3.0    3.0    4.0    4.0    4.0    3.0    3.0    3.0    3.0     4.0
0          [1, 1, 3, 1, 1, 1, 2]
1       [2, 2, 1, 1, 1, 1, 1, 1]
2    [1, 1, 1, 1, 1, 1, 1, 1, 2]
3          [2, 1, 1, 1, 3, 1, 1]
4                   [2, 3, 4, 1]
dtype: object
   maxLongString_NEO5  meanLongString_NEO5  countLongString_NEO5
0                 3.0             1.428571                   0.0
1                 2.0             1.250000                   0.0
2                 2.0             1.111111                   0.0
3                 3.0             1.428571                   0.0
4                 4.0             2.500000                   0.0

In [144]:
name = 'NEO6'
input_vars = construct_vars('NEO6_', 10)
validation, data = run_analysis(data, validation, name, input_vars, '1')

  NEO6_1 NEO6_2 NEO6_3 NEO6_4 NEO6_5 NEO6_6 NEO6_7 NEO6_8 NEO6_9 NEO6_10
0    1.0    4.0    5.0    4.0    2.0    5.0    5.0    5.0    2.0     5.0
1    3.0    4.0    5.0    3.0    1.0    1.0    1.0    5.0    4.0     4.0
2    1.0    1.0    5.0    2.0    4.0    2.0    1.0    4.0    2.0     4.0
3    3.0    3.0    5.0    3.0    3.0    4.0    5.0    3.0    3.0     4.0
4    2.0    4.0    5.0    4.0    1.0    3.0    4.0    3.0    5.0     5.0
0       [1, 1, 1, 1, 1, 3, 1, 1]
1          [1, 1, 1, 1, 3, 1, 2]
2    [2, 1, 1, 1, 1, 1, 1, 1, 1]
3          [2, 1, 2, 1, 1, 2, 1]
4    [1, 1, 1, 1, 1, 1, 1, 1, 2]
dtype: object
   maxLongString_NEO6  meanLongString_NEO6  countLongString_NEO6
0                 3.0             1.250000                   0.0
1                 3.0             1.428571                   0.0
2                 2.0             1.111111                   0.0
3                 2.0             1.428571                   0.0
4                 2.0             1.111111                   0.0

In [145]:
name = 'LEC_me'
input_vars = construct_vars('LEC1_', 17, '_1')
validation, data = run_analysis(data, validation, name, input_vars, '5')

     LEC1_1_1 LEC1_2_1 LEC1_3_1 LEC1_4_1 LEC1_5_1 LEC1_6_1 LEC1_7_1 LEC1_8_1  \
6148      1.0        0      1.0        0        0        0        0        0
6149        0        0      1.0        0        0        0        0        0
6150        0        0      1.0        0        0      1.0        0        0
6151      1.0        0      1.0        0        0        0        0        0
6152      1.0        0      1.0        0        0        0        0        0

     LEC1_9_1 LEC1_10_1 LEC1_11_1 LEC1_12_1 LEC1_13_1 LEC1_14_1 LEC1_15_1  \
6148        0         0         0         0         0         0         0
6149        0         0         0         0         0         0         0
6150        0         0         0         0         0         0         0
6151      1.0         0         0         0         0         0         0
6152      1.0         0         0         0         0         0         0

     LEC1_16_1 LEC1_17_1
6148         0       1.0
6149         0         0
6150         0         0
6151         0       1.0
6152         0         0
6148         [1, 1, 1, 13, 1]
6149               [2, 1, 14]
6150         [2, 1, 2, 1, 11]
6151    [1, 1, 1, 5, 1, 7, 1]
6152       [1, 1, 1, 5, 1, 8]
dtype: object
      maxLongString_LEC_me  meanLongString_LEC_me  countLongString_LEC_me
6148                  13.0               3.400000                     1.0
6149                  14.0               5.666667                     1.0
6150                  11.0               3.400000                     1.0
6151                   7.0               2.428571                     2.0
6152                   8.0               2.833333                     2.0

In [146]:
name = 'LEC_witness'
input_vars = construct_vars('LEC1_', 17, '_2')
validation, data = run_analysis(data, validation, name, input_vars, '5')

     LEC1_1_2 LEC1_2_2 LEC1_3_2 LEC1_4_2 LEC1_5_2 LEC1_6_2 LEC1_7_2 LEC1_8_2  \
6148      1.0        0      1.0        0        0        0      1.0        0
6149        0        0        0        0        0        0        0        0
6150        0        0        0        0        0        0        0        0
6151        0        0        0        0        0        0        0        0
6152        0        0        0        0        0        0        0        0

     LEC1_9_2 LEC1_10_2 LEC1_11_2 LEC1_12_2 LEC1_13_2 LEC1_14_2 LEC1_15_2  \
6148        0         0         0       1.0       1.0       1.0         0
6149        0         0         0         0         0         0         0
6150        0         0         0         0         0         0         0
6151        0         0         0         0         0         0         0
6152        0         0         0         0         0         0         0

     LEC1_16_2 LEC1_17_2
6148         0         0
6149         0         0
6150         0         0
6151         0         0
6152         0         0
6148    [1, 1, 1, 3, 1, 4, 3, 3]
6149                        [17]
6150                        [17]
6151                        [17]
6152                        [17]
dtype: object
      maxLongString_LEC_witness  meanLongString_LEC_witness  \
6148                        4.0                       2.125
6149                       17.0                      17.000
6150                       17.0                      17.000
6151                       17.0                      17.000
6152                       17.0                      17.000

      countLongString_LEC_witness
6148                          0.0
6149                          1.0
6150                          1.0
6151                          1.0
6152                          1.0

In [147]:
name = 'LEC_learned'
input_vars = construct_vars('LEC1_', 17, '_3')
validation, data = run_analysis(data, validation, name, input_vars, '5')

     LEC1_1_3 LEC1_2_3 LEC1_3_3 LEC1_4_3 LEC1_5_3 LEC1_6_3 LEC1_7_3 LEC1_8_3  \
6148      1.0        0      1.0        0        0        0        0        0
6149        0        0        0        0        0      1.0        0        0
6150        0        0        0        0        0        0        0        0
6151        0        0        0        0        0        0        0        0
6152        0        0        0        0        0        0        0      1.0

     LEC1_9_3 LEC1_10_3 LEC1_11_3 LEC1_12_3 LEC1_13_3 LEC1_14_3 LEC1_15_3  \
6148        0         0         0         0         0         0         0
6149        0         0         0         0         0         0         0
6150        0         0         0         0         0         0         0
6151        0         0         0         0         0         0         0
6152        0         0         0         0         0         0         0

     LEC1_16_3 LEC1_17_3
6148         0         0
6149         0         0
6150         0         0
6151         0         0
6152         0         0
6148    [1, 1, 1, 14]
6149       [5, 1, 11]
6150             [17]
6151             [17]
6152        [7, 1, 9]
dtype: object
      maxLongString_LEC_learned  meanLongString_LEC_learned  \
6148                       14.0                    4.250000
6149                       11.0                    5.666667
6150                       17.0                   17.000000
6151                       17.0                   17.000000
6152                        9.0                    5.666667

      countLongString_LEC_learned
6148                          1.0
6149                          2.0
6150                          1.0
6151                          1.0
6152                          2.0

In [148]:
name = 'LEC_job'
input_vars = construct_vars('LEC1_', 17, '_4')
validation, data = run_analysis(data, validation, name, input_vars, '5')

     LEC1_1_4 LEC1_2_4 LEC1_3_4 LEC1_4_4 LEC1_5_4 LEC1_6_4 LEC1_7_4 LEC1_8_4  \
6148        0        0        0        0        0        0        0        0
6149        0        0        0        0        0        0        0        0
6150        0        0        0        0        0        0        0        0
6151        0        0        0        0        0        0        0        0
6152        0        0        0        0        0        0        0        0

     LEC1_9_4 LEC1_10_4 LEC1_11_4 LEC1_12_4 LEC1_13_4 LEC1_14_4 LEC1_15_4  \
6148        0         0         0         0         0         0         0
6149        0         0         0         0         0         0         0
6150        0         0         0         0         0         0         0
6151        0         0         0         0         0         0         0
6152        0         0         0         0         0         0         0

     LEC1_16_4 LEC1_17_4
6148         0         0
6149         0         0
6150         0         0
6151         0         0
6152         0         0
6148    [17]
6149    [17]
6150    [17]
6151    [17]
6152    [17]
dtype: object
      maxLongString_LEC_job  meanLongString_LEC_job  countLongString_LEC_job
6148                   17.0                    17.0                      1.0
6149                   17.0                    17.0                      1.0
6150                   17.0                    17.0                      1.0
6151                   17.0                    17.0                      1.0
6152                   17.0                    17.0                      1.0

In [149]:
name = 'LEC_notSure'
input_vars = construct_vars('LEC1_', 17, '_5')
validation, data = run_analysis(data, validation, name, input_vars, '5')

     LEC1_1_5 LEC1_2_5 LEC1_3_5 LEC1_4_5 LEC1_5_5 LEC1_6_5 LEC1_7_5 LEC1_8_5  \
6148        0        0        0        0        0        0        0        0
6149        0        0        0        0        0        0        0        0
6150        0        0        0        0        0        0        0        0
6151        0        0        0        0        0        0        0        0
6152        0        0        0        0        0        0        0        0

     LEC1_9_5 LEC1_10_5 LEC1_11_5 LEC1_12_5 LEC1_13_5 LEC1_14_5 LEC1_15_5  \
6148        0         0         0         0         0         0         0
6149        0         0         0         0         0         0         0
6150        0         0         0         0         0         0         0
6151        0         0         0         0         0         0         0
6152        0         0         0         0       1.0         0         0

     LEC1_16_5 LEC1_17_5
6148         0         0
6149         0         0
6150         0         0
6151         0         0
6152         0         0
6148          [17]
6149          [17]
6150          [17]
6151          [17]
6152    [12, 1, 4]
dtype: object
      maxLongString_LEC_notSure  meanLongString_LEC_notSure  \
6148                       17.0                   17.000000
6149                       17.0                   17.000000
6150                       17.0                   17.000000
6151                       17.0                   17.000000
6152                       12.0                    5.666667

      countLongString_LEC_notSure
6148                          1.0
6149                          1.0
6150                          1.0
6151                          1.0
6152                          1.0

In [150]:
name = 'LEC_NA'
input_vars = construct_vars('LEC1_', 17, '_6')
validation, data = run_analysis(data, validation, name, input_vars, '5')

     LEC1_1_6 LEC1_2_6 LEC1_3_6 LEC1_4_6 LEC1_5_6 LEC1_6_6 LEC1_7_6 LEC1_8_6  \
6148        0      1.0        0      1.0      1.0      1.0        0      1.0
6149      1.0      1.0        0      1.0      1.0        0      1.0      1.0
6150      1.0      1.0        0      1.0      1.0        0      1.0      1.0
6151        0      1.0        0      1.0      1.0      1.0      1.0      1.0
6152        0      1.0        0      1.0      1.0      1.0      1.0        0

     LEC1_9_6 LEC1_10_6 LEC1_11_6 LEC1_12_6 LEC1_13_6 LEC1_14_6 LEC1_15_6  \
6148      1.0       1.0       1.0         0         0         0       1.0
6149      1.0       1.0       1.0       1.0       1.0       1.0       1.0
6150      1.0       1.0       1.0       1.0       1.0       1.0       1.0
6151        0       1.0       1.0       1.0       1.0       1.0       1.0
6152        0       1.0       1.0       1.0         0       1.0       1.0

     LEC1_16_6 LEC1_17_6
6148       1.0         0
6149       1.0       1.0
6150       1.0       1.0
6151       1.0         0
6152       1.0       1.0
6148    [1, 1, 1, 3, 1, 4, 3, 2, 1]
6149               [2, 1, 2, 1, 11]
6150               [2, 1, 2, 1, 11]
6151          [1, 1, 1, 5, 1, 7, 1]
6152       [1, 1, 1, 4, 2, 3, 1, 4]
dtype: object
      maxLongString_LEC_NA  meanLongString_LEC_NA  countLongString_LEC_NA
6148                   4.0               1.888889                     0.0
6149                  11.0               3.400000                     1.0
6150                  11.0               3.400000                     1.0
6151                   7.0               2.428571                     2.0
6152                   4.0               2.125000                     0.0

In [151]:
validation.to_csv('output/validation.csv', index=False)

In [152]:
input_vars

['LEC1_1_6',
 'LEC1_2_6',
 'LEC1_3_6',
 'LEC1_4_6',
 'LEC1_5_6',
 'LEC1_6_6',
 'LEC1_7_6',
 'LEC1_8_6',
 'LEC1_9_6',
 'LEC1_10_6',
 'LEC1_11_6',
 'LEC1_12_6',
 'LEC1_13_6',
 'LEC1_14_6',
 'LEC1_15_6',
 'LEC1_16_6',
 'LEC1_17_6']

In [153]:
validation = validation.loc[~validation['PROLIFIC_PID'].isna()]

In [154]:
validation.shape

(11110, 341)

In [155]:
validation.loc[validation['wave']=='A']

,PROLIFIC_PID,wave,total_time,failed_att_qns_1,failed_att_qns_2,failed_att_qns_3,failed_att_qns_4,failed_att_qns_5,completed,in_include_list_w1,...,countLongString_LEC_learned,maxLongString_LEC_job,meanLongString_LEC_job,countLongString_LEC_job,maxLongString_LEC_notSure,meanLongString_LEC_notSure,countLongString_LEC_notSure,maxLongString_LEC_NA,meanLongString_LEC_NA,countLongString_LEC_NA
10873,CC0186,A,43.0,False,False,True,False,NaN,1,False,...,2.0,9.0,9.00,1.0,17.0,17.000000,1.0,6.0,3.400000,2.0
10874,CC0144,A,147.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,8.0,3.400000,2.0
10875,CC0172,A,114.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,11.0,3.400000,1.0
10876,CC0165,A,15.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,10.0,5.666667,2.0,15.0,5.666667,1.0
10877,CC0117,A,81.0,False,False,False,False,NaN,1,False,...,1.0,3.0,1.50,0.0,17.0,17.000000,1.0,15.0,5.666667,1.0
10878,CC0087,A,79.0,False,True,False,False,NaN,1,False,...,2.0,9.0,9.00,1.0,17.0,17.000000,1.0,6.0,2.125000,1.0
10879,CC0137,A,74.0,False,False,True,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,9.0,3.400000,1.0
10880,CC0191,A,149.0,False,False,False,False,NaN,1,False,...,0.0,6.0,3.00,1.0,17.0,17.000000,1.0,9.0,2.428571,1.0
10881,CC0063,A,156.0,True,True,True,True,NaN,1,False,...,1.0,8.0,4.50,1.0,14.0,4.250000,1.0,17.0,17.000000,1.0
10882,CC0177,A,217.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,4.0,2.428571,0.0
10883,CC0111,A,100.0,False,False,True,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,4.0,2.125000,0.0
10884,CC0053,A,114.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,13.0,5.666667,1.0
10885,CC0026,A,89.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,5.0,2.428571,1.0
10886,CC0005,A,117.0,True,False,False,False,NaN,1,False,...,1.0,5.0,1.80,1.0,17.0,17.000000,1.0,15.0,5.666667,1.0
10887,CC0189,A,157.0,True,False,True,False,NaN,1,False,...,1.0,4.0,2.25,0.0,13.0,5.666667,1.0,9.0,3.400000,1.0
10888,CC0076,A,172.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,5.0,2.428571,1.0
10889,CC0041,A,99.0,True,False,False,False,NaN,1,False,...,0.0,9.0,9.00,1.0,17.0,17.000000,1.0,7.0,3.400000,1.0
10890,CC0159,A,99.0,True,False,False,False,NaN,1,False,...,2.0,9.0,9.00,1.0,16.0,8.500000,1.0,4.0,1.700000,0.0
10891,CC0118,A,95.0,True,False,False,False,NaN,1,False,...,2.0,4.0,2.25,0.0,17.0,17.000000,1.0,4.0,1.888889,0.0
10892,CC0012,A,189.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,11.0,3.400000,1.0
10893,CC0114,A,109.0,True,False,True,False,NaN,1,False,...,0.0,9.0,9.00,1.0,17.0,17.000000,1.0,9.0,4.250000,1.0
10894,CC0161,A,129.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,4.0,2.428571,0.0
10895,CC0003,A,60.0,True,False,False,False,NaN,1,False,...,2.0,9.0,9.00,1.0,17.0,17.000000,1.0,4.0,1.700000,0.0
10896,CC0046,A,128.0,True,False,False,False,NaN,1,False,...,2.0,9.0,9.00,1.0,10.0,5.666667,2.0,7.0,2.428571,1.0
10897,CC0101,A,168.0,True,False,False,False,NaN,1,False,...,0.0,9.0,9.00,1.0,17.0,17.000000,1.0,4.0,2.428571,0.0
10898,CC0008,A,138.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,16.0,8.500000,1.0,15.0,5.666667,1.0
10899,CC0142,A,102.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,13.0,3.400000,1.0
10900,CC0173,A,151.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,13.0,4.250000,1.0
10901,CC0154,A,795.0,True,True,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,14.0,5.666667,1.0,10.0,3.400000,1.0
10902,CC0007,A,137.0,True,False,False,False,NaN,1,False,...,1.0,4.0,3.00,0.0,16.0,8.500000,1.0,15.0,5.666667,1.0
10903,CC0069,A,138.0,True,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,15.0,5.666667,1.0
10904,CC0166,A,75.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,14.0,5.666667,1.0
10905,CC0157,A,122.0,False,False,True,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,10.0,3.400000,1.0
10906,CC0100,A,123.0,False,False,False,False,NaN,1,False,...,1.0,6.0,4.50,1.0,12.0,5.666667,1.0,10.0,3.400000,1.0
10907,CC0143,A,48.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,8.0,5.666667,2.0,7.0,2.833333,2.0
10908,CC0184,A,88.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,5.0,1.545455,1.0
10909,CC0059,A,379.0,True,False,False,False,NaN,1,False,...,0.0,9.0,9.00,1.0,12.0,4.250000,1.0,4.0,1.545455,0.0
10910,CC0145,A,128.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,10.0,3.400000,1.0
10911,CC0049,A,137.0,True,False,True,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,14.0,4.250000,1.0
10912,CC0070,A,62.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,9.0,3.400000,1.0,10.0,3.400000,1.0
10913,CC0135,A,108.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,14.0,5.666667,1.0
10914,CC0068,A,1085.0,False,False,True,False,NaN,1,False,...,0.0,7.0,4.50,1.0,10.0,3.400000,1.0,17.0,17.000000,1.0
10915,CC0055,A,104.0,False,False,True,False,NaN,1,False,...,2.0,9.0,9.00,1.0,16.0,8.500000,1.0,6.0,1.888889,1.0
10916,CC0078,A,856.0,False,True,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,6.0,1.700000,1.0
10917,CC0108,A,57.0,False,False,False,False,NaN,1,False,...,1.0,9.0,9.00,1.0,17.0,17.000000,1.0,10.0,3.400000,1.0

In [156]:
test = data.loc[data['PROLIFIC_PID']=='5e52148e9a302e245eb71caf']

In [157]:
test[['wave', 'V3', 'V4', 'V5']]

      wave                   V3                   V4 V5
427      1         4/5/20 11:05         4/5/20 12:32  1
2957     2         4/11/20 9:25        4/11/20 10:40  1
4347     3         4/18/20 7:10         4/18/20 8:40  1
5649     4         4/25/20 7:57         4/25/20 9:02  1
7233     5         5/9/20 10:06         5/9/20 11:52  1
8580     6        5/24/20 12:03        5/24/20 13:31  1
9612     7         6/7/20 15:05         6/7/20 16:25  1
10832    8  2020-06-29 02:29:01  2020-06-29 04:00:41  1

In [158]:
test

,AnxS1_1,AnxS1_2,AnxS1_3,AnxS1_4,AnxS1_5,AnxS1_6,AnxS1_7,AnxS1_8,AnxS1_9,AnxS1_10,...,norm1,norm2,norm3,norm4,pavLink,resource1,resource2,resource_pre,resources1,wave
427,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/pro_iat/index.html?S...,NaN,NaN,NaN,NaN,1
2957,4.0,4.0,1.0,1.0,4.0,1.0,1.0,3.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/pro_iat/index.html?S...,NaN,NaN,NaN,NaN,2
4347,4.0,4.0,1.0,1.0,4.0,1.0,2.0,4.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/tr_1s/index.html?SID...,1.0,1.0,1.0,NaN,3
5649,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_altt/index_respR...,1.0,1.0,1.0,NaN,4
7233,4.0,4.0,2.0,1.0,3.0,1.0,3.0,3.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_amp/index.html?S...,1.0,1.0,1.0,NaN,5
8580,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_altt/index_respR...,1.0,1.0,1.0,NaN,6
9612,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_altt/index_respR...,1.0,1.0,1.0,NaN,7
10832,2.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,1.0,3.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_altt/index_respR...,1.0,1.0,1.0,NaN,8

In [159]:
data

,AnxS1_1,AnxS1_2,AnxS1_3,AnxS1_4,AnxS1_5,AnxS1_6,AnxS1_7,AnxS1_8,AnxS1_9,AnxS1_10,...,norm1,norm2,norm3,norm4,pavLink,resource1,resource2,resource_pre,resources1,wave
0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,1.0,3.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_pgg/index.html?S...,NaN,NaN,NaN,NaN,1
1,1.0,1.0,4.0,4.0,1.0,2.0,4.0,1.0,4.0,1.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_amp/index.html?S...,NaN,NaN,NaN,NaN,1
2,3.0,3.0,2.0,1.0,3.0,1.0,1.0,2.0,1.0,3.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_pgg/index.html?S...,NaN,NaN,NaN,NaN,1
3,2.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,2.0,2.0,...,1.0,4.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_amp/index.html?S...,NaN,NaN,NaN,NaN,1
4,2.0,2.0,3.0,3.0,2.0,3.0,3.0,2.0,3.0,1.0,...,1.0,2.0,4.0,3.0,pavlovia.org/run/dstanley/cvd_amp/index.html?S...,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,3.0,3.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/tr_1s_conte/index.ht...,NaN,NaN,1.0,NaN,E
11106,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/cvd_altt_conte/index...,NaN,NaN,1.0,"<span style=""font-size:16px;"">I&#39;m ready to...",E
11107,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,4.0,4.0,5.0,pavlovia.org/run/dstanley/cvd_pgg_conte/index....,NaN,NaN,1.0,NaN,E
11108,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,1.0,4.0,...,1.0,2.0,3.0,5.0,pavlovia.org/run/dstanley/cvd_altt_conte/index...,NaN,NaN,1.0,"<span style=""font-size:16px;"">I&#39;m ready to...",E
11109,3.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,4.0,...,1.0,5.0,5.0,5.0,pavlovia.org/run/dstanley/tr_1s_conte/index.ht...,NaN,NaN,1.0,"<span style=""font-size:16px;"">I&#39;m ready to...",E

In [160]:
validation.loc[validation['PROLIFIC_PID']=='5e52148e9a302e245eb71caf']

,PROLIFIC_PID,wave,total_time,failed_att_qns_1,failed_att_qns_2,failed_att_qns_3,failed_att_qns_4,failed_att_qns_5,completed,in_include_list_w1,...,countLongString_LEC_learned,maxLongString_LEC_job,meanLongString_LEC_job,countLongString_LEC_job,maxLongString_LEC_notSure,meanLongString_LEC_notSure,countLongString_LEC_notSure,maxLongString_LEC_NA,meanLongString_LEC_NA,countLongString_LEC_NA
427,5e52148e9a302e245eb71caf,1,87.000000,False,False,False,NaN,NaN,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2957,5e52148e9a302e245eb71caf,2,75.000000,False,False,NaN,NaN,NaN,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4347,5e52148e9a302e245eb71caf,3,90.000000,False,False,False,NaN,NaN,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5649,5e52148e9a302e245eb71caf,4,65.000000,False,False,True,NaN,NaN,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7233,5e52148e9a302e245eb71caf,5,106.000000,False,False,False,NaN,NaN,1,True,...,1.0,17.0,17.0,1.0,13.0,5.666667,1.0,4.0,2.125,0.0
8580,5e52148e9a302e245eb71caf,6,88.000000,False,False,False,NaN,NaN,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9612,5e52148e9a302e245eb71caf,7,80.000000,False,False,False,NaN,NaN,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10832,5e52148e9a302e245eb71caf,8,91.666667,False,False,False,NaN,NaN,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
data.shape

(11110, 2499)

In [162]:
validation.shape

(11110, 341)

## 5. Z-scoring and transformation (outdated)

In [163]:
validation.shape

(11110, 341)

In [164]:
validation.to_csv('output/validation.csv', index=False)

In [432]:
# transform and z-scoring
from scipy.stats import boxcox
transform_mean = validation.filter(regex='meanLongString', axis=1).apply(lambda x: boxcox(x, -2), axis=0)

In [433]:
plt.hist(transform_mean['meanLongString_STAI_state'])

NameError: name 'plt' is not defined

In [ ]:
transform_max = validation.filter(regex='maxLongString', axis=1).apply(lambda x: boxcox(x, -0.1), axis=0)

In [ ]:
transform_max.head()

In [ ]:
plt.hist(validation['maxLongString_disgust_COVID'])

In [ ]:
plt.hist(transform_max['maxLongString_disgust_COVID'])

In [1447]:
transform_all = pd.concat([transform_max, transform_mean], axis=1)
z_transform_all = transform_all.copy()

In [1448]:
transform_all[['PROLIFIC_PID', 'wave']] = validation[['PROLIFIC_PID', 'wave']]

In [1449]:
z_transform_all['maxLongString_PANA']

0       1.294494
1       1.294494
2       0.669670
3       1.972584
4       2.056718
          ...
9792    1.040415
9793    0.669670
9794    1.040415
9795    0.669670
9796    1.040415
Name: maxLongString_PANA, Length: 9797, dtype: float64

In [1432]:
z_transform_all.loc[z_transform_all['wave']=='1'].std()

maxLongString_PANA             0.410076
maxLongString_STAI_state       0.303857
maxLongString_disgust_COVID    0.338672
maxLongString_fear_COVID       0.420151
maxLongString_EMSB             0.510563
                                 ...
meanLongString_LEC_witness          NaN
meanLongString_LEC_learned          NaN
meanLongString_LEC_job              NaN
meanLongString_LEC_notSure          NaN
meanLongString_LEC_NA               NaN
Length: 198, dtype: float64

In [1451]:
z_transform_all.loc[transform_all['wave']=='1'].apply(lambda x: (x - x.mean())/x.std(), axis=0)

,maxLongString_PANA,maxLongString_STAI_state,maxLongString_disgust_COVID,maxLongString_fear_COVID,maxLongString_EMSB,maxLongString_EMSC,maxLongString_NIHE,maxLongString_NIHL,maxLongString_BDI,maxLongString_CD_RISK,...,meanLongString_NEO3,meanLongString_NEO4,meanLongString_NEO5,meanLongString_NEO6,meanLongString_LEC_me,meanLongString_LEC_witness,meanLongString_LEC_learned,meanLongString_LEC_job,meanLongString_LEC_notSure,meanLongString_LEC_NA
0,0.347903,2.327598,1.998401,2.327279,1.070768,1.410916,0.043704,0.138760,NaN,NaN,...,2.433204,1.234774,2.026399,1.813862,NaN,NaN,NaN,NaN,NaN,NaN
1,0.347903,-0.067842,-0.867921,0.016820,0.573123,0.523704,-0.981146,-0.737125,NaN,NaN,...,1.702892,1.234774,0.415791,0.660359,NaN,NaN,NaN,NaN,NaN,NaN
2,-1.175777,1.400562,0.977006,0.016820,-0.153027,-0.213500,-0.981146,-0.737125,NaN,NaN,...,-0.853199,0.600806,-1.146011,-0.877644,NaN,NaN,NaN,NaN,NaN,NaN
3,2.001474,0.768337,0.977006,0.899230,1.070768,0.523704,0.043704,1.192873,NaN,NaN,...,1.702892,1.771209,2.368043,1.285173,NaN,NaN,NaN,NaN,NaN,NaN
4,2.206640,-0.067842,0.977006,-1.577059,0.573123,1.028924,0.396995,1.192873,NaN,NaN,...,0.607425,-0.130696,1.587142,-0.877644,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,-0.271687,1.400562,0.977006,0.016820,0.573123,0.523704,0.941511,-0.737125,NaN,NaN,...,-0.077243,-1.886301,-2.073331,-0.877644,NaN,NaN,NaN,NaN,NaN,NaN
1793,-0.271687,-0.067842,0.226784,0.016820,0.573123,0.523704,0.941511,1.192873,NaN,NaN,...,-1.720444,-0.130696,-0.316304,0.660359,NaN,NaN,NaN,NaN,NaN,NaN
1794,-0.271687,-1.287971,-0.867921,0.016820,1.070768,0.523704,-1.832716,-0.737125,NaN,NaN,...,-0.077243,0.600806,0.415791,1.285173,NaN,NaN,NaN,NaN,NaN,NaN
1795,-0.271687,-0.067842,0.226784,0.016820,0.573123,0.523704,-0.981146,-0.737125,NaN,NaN,...,-0.853199,0.600806,-0.316304,1.813862,NaN,NaN,NaN,NaN,NaN,NaN
1796,-0.271687,-0.067842,0.977006,0.016820,-1.464657,-1.545097,0.941511,1.192873,NaN,NaN,...,-0.853199,-1.886301,-0.316304,-0.060580,NaN,NaN,NaN,NaN,NaN,NaN

In [1452]:
for i in range(7):
    w = str(i+1)
    z_transform_all.loc[transform_all['wave']==w] = z_transform_all.loc[transform_all['wave']==w].apply(lambda x: (x - x.mean())/x.std(), axis=1)

In [1454]:
z_transform_all[['PROLIFIC_PID', 'wave']] = transform_all[['PROLIFIC_PID', 'wave']]

In [1455]:
z_transform_all.to_csv('output/validation_z_scored_long_string.csv', index=False)
transform_all.to_csv('output/validation_boxcox_transform.csv', index=False)

## 6. Calculate interquartile range

In [165]:
def interq_range(s, n):
    # calculate the intequartile range given a pandas series - a list of responses
    s_cleaned = s[~s.isna()]
    if len(s_cleaned) == 0:
        return [np.nan, np.nan]
    else:
        q1 = np.quantile(s_cleaned.astype(float), 0.25)
        q3 = np.quantile(s_cleaned.astype(float), 0.75)
        return [q1-n*(q3-q1), q3+n*(q3-q1)]

def interq_analysis_old(dat, n_w, n_q, validation):
    dat_tmp = dat.copy()
    for w in n_w:
        interq_r = dat.loc[validation['wave'] == w].apply(lambda x: interq_range(x, 1), axis=0)
        print(interq_r)
        for col in list(interq_r.index):
            dat_no_na = dat.loc[(validation['wave'] == w) & (~dat[col].isna())]
            if ~np.any(np.isnan(interq_r[col])):
                idx = (validation['wave'] == w) & (dat_no_na[col]<=interq_r[col][1]) & (dat_no_na[col]>=interq_r[col][0])
                dat_tmp.loc[idx, col] = 0

    for q in range(n_q):
        for w in n_w:
            interq_r = dat.loc[validation['wave'] == w].apply(lambda x: interq_range(x, q+1), axis=0)
            for col in list(interq_r.index):
                dat_no_na = dat.loc[(validation['wave'] == w) & (~dat[col].isna())]
                if ~np.any(np.isnan(interq_r[col])):
                    idx = (validation['wave'] == w) & ((dat_no_na[col]<interq_r[col][0]) | (dat_no_na[col]>interq_r[col][1]))
                    dat_tmp.loc[idx, col] = q+1
    return dat_tmp


def interq_analysis(dat, n_w, n_q, validation):
    dat_tmp = dat.copy()
    for w in n_w:
        interq_r = dat.loc[validation['wave'] == w].apply(lambda x: interq_range(x, 1), axis=0)
        for col in list(interq_r.columns):
            dat_no_na = dat.loc[(validation['wave'] == w) & (~dat[col].isna())]
            if ~np.any(np.isnan(interq_r[col])):
                idx = (validation['wave'] == w) & (dat_no_na[col]<=interq_r[col][1]) & (dat_no_na[col]>=interq_r[col][0])
                dat_tmp.loc[idx, col] = 0

    for q in range(n_q):
        for w in n_w:
            interq_r = dat.loc[validation['wave'] == w].apply(lambda x: interq_range(x, q+1), axis=0)
            for col in list(interq_r.columns):
                dat_no_na = dat.loc[(validation['wave'] == w) & (~dat[col].isna())]
                if ~np.any(np.isnan(interq_r[col])):
                    idx = (validation['wave'] == w) & ((dat_no_na[col]<interq_r[col][0]) | (dat_no_na[col]>interq_r[col][1]))
                    dat_tmp.loc[idx, col] = q+1
    return dat_tmp

In [166]:
rs_mean = validation.filter(regex='meanLongString', axis=1)

In [167]:
interq_r = rs_mean.loc[validation['wave'] == '1'].apply(lambda x: interq_range(x, 1), axis=0)

In [168]:
interq_rs_mean = interq_analysis(rs_mean, n_w, 3, validation)

In [169]:
rs_max = validation.filter(regex='maxLongString', axis=1)

In [170]:
interq_rs_max = interq_analysis(rs_max, n_w, 3, validation)

In [171]:
interq_rs = pd.concat([interq_rs_mean, interq_rs_max], axis=1)
interq_rs['wave'] = data['wave']
interq_rs['PROLIFIC_PID'] = data['PROLIFIC_PID']

In [172]:
interq_rs = interq_rs.loc[~interq_rs['PROLIFIC_PID'].isna()]

In [173]:
interq_rs.shape

(11110, 200)

In [174]:
interq_rs.to_csv('validation_interquartile_classification.csv', index=False)

In [181]:
interq_rs

,meanLongString_PANA,meanLongString_STAI_state,meanLongString_disgust_COVID,meanLongString_fear_COVID,meanLongString_EMSB,meanLongString_EMSC,meanLongString_NIHE,meanLongString_NIHL,meanLongString_BDI,meanLongString_CD_RISK,...,maxLongString_NEO5,maxLongString_NEO6,maxLongString_LEC_me,maxLongString_LEC_witness,maxLongString_LEC_learned,maxLongString_LEC_job,maxLongString_LEC_notSure,maxLongString_LEC_NA,wave,PROLIFIC_PID
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,5df82e8739bcde5dd044f741
1,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,5c7e91c1973c990016ea72b0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,5e753094e8a6f10a9805ed9a
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,5e67052c757e6149c38ce468
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,5e7745990fd39b2a816ec341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,3.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,E,CC0183
11106,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,3.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,E,CC0145
11107,0.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,NaN,...,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,E,CC0053
11108,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,E,CC0184
11109,3.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,3.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,E,CC0162

# 7. Additional IQR variables

In [184]:
add_data = pd.read_csv('Working_Data/additional_IQRmeasures.csv', index_col=0)

In [185]:
add_data.loc[add_data['PROLIFIC_PID']=='5e52148e9a302e245eb71caf']

,PROLIFIC_PID,wave,PANAS_diff,PANASpos_PSS_diff,STAI_diff,EES_empFeelExp_diff,EES_empPers_diff,Disg_diff,NaN_Freq1,NaN_Freq2,NaN_Freq3
427,5e52148e9a302e245eb71caf,1,3.3,NaN,2.7,NaN,NaN,1.300000,NaN,0.00,NaN
2957,5e52148e9a302e245eb71caf,2,2.6,1.5,2.7,NaN,NaN,1.272727,NaN,0.00,NaN
4347,5e52148e9a302e245eb71caf,3,2.7,0.5,2.6,NaN,NaN,NaN,0.1,0.25,NaN
5649,5e52148e9a302e245eb71caf,4,3.4,2.0,2.9,2.25,0.666667,NaN,0.1,0.00,NaN
7234,5e52148e9a302e245eb71caf,5,1.9,0.3,2.2,NaN,NaN,1.172727,0.0,0.00,0.0
8581,5e52148e9a302e245eb71caf,6,2.8,0.9,2.8,NaN,NaN,NaN,0.2,0.25,0.0
9613,5e52148e9a302e245eb71caf,7,3.2,1.7,2.8,NaN,NaN,NaN,0.2,0.00,NaN
10833,5e52148e9a302e245eb71caf,8,1.6,0.5,1.4,3.25,3.250000,1.263636,0.3,0.00,NaN

In [186]:
add_data

,PROLIFIC_PID,wave,PANAS_diff,PANASpos_PSS_diff,STAI_diff,EES_empFeelExp_diff,EES_empPers_diff,Disg_diff,NaN_Freq1,NaN_Freq2,NaN_Freq3
0,5df82e8739bcde5dd044f741,1,2.8,NaN,0.8,NaN,NaN,0.590909,NaN,0.875,NaN
1,5c7e91c1973c990016ea72b0,1,0.1,NaN,1.9,NaN,NaN,1.527273,NaN,0.000,NaN
2,5e753094e8a6f10a9805ed9a,1,0.7,NaN,1.4,NaN,NaN,0.754545,NaN,0.000,NaN
3,5e67052c757e6149c38ce468,1,0.3,NaN,0.7,NaN,NaN,1.118182,NaN,0.000,NaN
4,5e7745990fd39b2a816ec341,1,0.3,NaN,0.8,NaN,NaN,0.427273,NaN,0.000,NaN
...,...,...,...,...,...,...,...,...,...,...,...
11106,CC0183,E,2.2,1.1,1.9,4.333333,3.750000,0.281818,0.0,0.000,NaN
11107,CC0145,E,4.0,2.4,3.0,4.583333,5.000000,2.290909,0.0,0.000,NaN
11108,CC0053,E,2.7,0.6,0.0,NaN,NaN,0.327273,0.0,0.000,NaN
11109,CC0184,E,2.7,0.7,3.0,2.666667,1.083333,0.145455,0.0,0.000,NaN
11110,CC0162,E,0.0,1.7,1.7,1.416667,2.416667,1.354545,0.0,0.000,NaN

In [187]:
p_dat = add_data.drop(['PROLIFIC_PID', 'wave'], axis=1)

In [188]:
p_dat

,PANAS_diff,PANASpos_PSS_diff,STAI_diff,EES_empFeelExp_diff,EES_empPers_diff,Disg_diff,NaN_Freq1,NaN_Freq2,NaN_Freq3
0,2.8,NaN,0.8,NaN,NaN,0.590909,NaN,0.875,NaN
1,0.1,NaN,1.9,NaN,NaN,1.527273,NaN,0.000,NaN
2,0.7,NaN,1.4,NaN,NaN,0.754545,NaN,0.000,NaN
3,0.3,NaN,0.7,NaN,NaN,1.118182,NaN,0.000,NaN
4,0.3,NaN,0.8,NaN,NaN,0.427273,NaN,0.000,NaN
...,...,...,...,...,...,...,...,...,...
11106,2.2,1.1,1.9,4.333333,3.750000,0.281818,0.0,0.000,NaN
11107,4.0,2.4,3.0,4.583333,5.000000,2.290909,0.0,0.000,NaN
11108,2.7,0.6,0.0,NaN,NaN,0.327273,0.0,0.000,NaN
11109,2.7,0.7,3.0,2.666667,1.083333,0.145455,0.0,0.000,NaN
11110,0.0,1.7,1.7,1.416667,2.416667,1.354545,0.0,0.000,NaN

In [189]:
n_w = ['1','2','3','4','5','6','7','8', 'A', 'B', 'C', 'D', 'E']
interq_add = interq_analysis(p_dat, n_w, 3, add_data)

In [190]:
interq_add['wave'] = add_data['wave']
interq_add['PROLIFIC_PID'] = add_data['PROLIFIC_PID']

In [191]:
interq_add

,PANAS_diff,PANASpos_PSS_diff,STAI_diff,EES_empFeelExp_diff,EES_empPers_diff,Disg_diff,NaN_Freq1,NaN_Freq2,NaN_Freq3,wave,PROLIFIC_PID
0,0.0,NaN,0.0,NaN,NaN,0.0,NaN,3.0,NaN,1,5df82e8739bcde5dd044f741
1,0.0,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,1,5c7e91c1973c990016ea72b0
2,0.0,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,1,5e753094e8a6f10a9805ed9a
3,0.0,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,1,5e67052c757e6149c38ce468
4,0.0,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,1,5e7745990fd39b2a816ec341
...,...,...,...,...,...,...,...,...,...,...,...
11106,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,E,CC0183
11107,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,E,CC0145
11108,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,E,CC0053
11109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,E,CC0184
11110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,E,CC0162

In [192]:
interq_add.shape

(11111, 11)

In [194]:
all_interq = interq_rs.merge(interq_add, on=['PROLIFIC_PID', 'wave'], how='left')

In [195]:
all_interq.to_csv('all_IQRmeasures_output.csv', index=None)

In [472]:
task_conte = pd.read_csv('Working_Data/task_validation_conte.csv')

In [473]:
task_conte_dat = task_conte.drop(['PROLIFIC_PID', 'wave'], axis=1)

In [474]:
n_w = ['A', 'B', 'C', 'D', 'E']
interq_add = interq_analysis(task_conte_dat, n_w, 3, task_conte)

In [476]:
interq_add['wave'] = task_conte['wave']
interq_add['PROLIFIC_PID'] = task_conte['PROLIFIC_PID']

In [479]:
task_conte

,PROLIFIC_PID,tr_1s_rt_pctlt_300,tr_1s_medianRT,tr_1s_noVar,tr_1s_totalTime,tr_1s_meanLongString,iat_include,iat_totalTime,amp_pct_bad_rts,amp_medianRT,...,pgg_totalTime,wave,tr,proiat,amp,altt,pgg,biat_include,biat_totalTime,biat
0,CC0003,0.000000,2724.5,0.0,3.091783,1.11,1.0,3.618700,0.0,767.0,...,1.655150,A,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
1,CC0005,0.000000,3092.5,0.0,4.229517,1.57,1.0,6.039650,0.0,617.0,...,5.073250,A,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
2,CC0007,0.000000,1904.0,1.0,3.454333,60.00,1.0,6.987383,0.0,522.0,...,4.237500,A,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
3,CC0008,0.000000,3076.5,1.0,3.709950,60.00,1.0,6.443500,0.0,966.0,...,3.190700,A,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
4,CC0012,0.016667,976.0,0.0,2.289533,1.20,1.0,5.511583,0.0,430.0,...,3.870817,A,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,CC0183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.202683,E,0.0,NaN,NaN,NaN,NaN,3.0,4.141367,NaN
211,CC0184,0.000000,1514.5,0.0,4.034567,1.64,NaN,NaN,NaN,NaN,...,2.387367,E,NaN,NaN,NaN,NaN,NaN,3.0,5.837033,NaN
212,CC0186,0.000000,2639.0,0.0,3.464633,1.51,NaN,NaN,NaN,NaN,...,1.776817,E,NaN,NaN,NaN,NaN,NaN,3.0,5.892617,NaN
213,CC0189,0.000000,595.5,1.0,1.304917,60.00,NaN,NaN,NaN,NaN,...,1.648867,E,NaN,NaN,NaN,NaN,NaN,3.0,5.157350,NaN
214,CC0190,0.000000,2403.5,0.0,3.170000,1.19,NaN,NaN,NaN,NaN,...,1.083083,E,NaN,NaN,NaN,NaN,NaN,3.0,4.817133,NaN

In [477]:
interq_add

,tr_1s_rt_pctlt_300,tr_1s_medianRT,tr_1s_noVar,tr_1s_totalTime,tr_1s_meanLongString,iat_include,iat_totalTime,amp_pct_bad_rts,amp_medianRT,amp_meanLongString,...,tr,proiat,amp,altt,pgg,biat_include,biat_totalTime,biat,wave,PROLIFIC_PID
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,A,CC0003
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,A,CC0005
2,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,A,CC0007
3,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,A,CC0008
4,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,A,CC0012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,E,CC0183
211,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,E,CC0184
212,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,E,CC0186
213,0.0,0.0,3.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,E,CC0189
214,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,E,CC0190

In [478]:
interq_add.to_csv('output/task_validation_conte_IQR.csv', index=None)